
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QuestionAnswer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model QuestionAnswer
 * 
 */
export type QuestionAnswerModel = runtime.Types.Result.DefaultSelection<Prisma.$QuestionAnswerPayload>

export type AggregateQuestionAnswer = {
  _count: QuestionAnswerCountAggregateOutputType | null
  _min: QuestionAnswerMinAggregateOutputType | null
  _max: QuestionAnswerMaxAggregateOutputType | null
}

export type QuestionAnswerMinAggregateOutputType = {
  id: string | null
  questionId: string | null
  submissionId: string | null
  selectedOptionId: string | null
  isCorrect: boolean | null
}

export type QuestionAnswerMaxAggregateOutputType = {
  id: string | null
  questionId: string | null
  submissionId: string | null
  selectedOptionId: string | null
  isCorrect: boolean | null
}

export type QuestionAnswerCountAggregateOutputType = {
  id: number
  questionId: number
  submissionId: number
  selectedOptionId: number
  isCorrect: number
  _all: number
}


export type QuestionAnswerMinAggregateInputType = {
  id?: true
  questionId?: true
  submissionId?: true
  selectedOptionId?: true
  isCorrect?: true
}

export type QuestionAnswerMaxAggregateInputType = {
  id?: true
  questionId?: true
  submissionId?: true
  selectedOptionId?: true
  isCorrect?: true
}

export type QuestionAnswerCountAggregateInputType = {
  id?: true
  questionId?: true
  submissionId?: true
  selectedOptionId?: true
  isCorrect?: true
  _all?: true
}

export type QuestionAnswerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuestionAnswer to aggregate.
   */
  where?: Prisma.QuestionAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionAnswers to fetch.
   */
  orderBy?: Prisma.QuestionAnswerOrderByWithRelationInput | Prisma.QuestionAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuestionAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuestionAnswers
  **/
  _count?: true | QuestionAnswerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuestionAnswerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuestionAnswerMaxAggregateInputType
}

export type GetQuestionAnswerAggregateType<T extends QuestionAnswerAggregateArgs> = {
      [P in keyof T & keyof AggregateQuestionAnswer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuestionAnswer[P]>
    : Prisma.GetScalarType<T[P], AggregateQuestionAnswer[P]>
}




export type QuestionAnswerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuestionAnswerWhereInput
  orderBy?: Prisma.QuestionAnswerOrderByWithAggregationInput | Prisma.QuestionAnswerOrderByWithAggregationInput[]
  by: Prisma.QuestionAnswerScalarFieldEnum[] | Prisma.QuestionAnswerScalarFieldEnum
  having?: Prisma.QuestionAnswerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuestionAnswerCountAggregateInputType | true
  _min?: QuestionAnswerMinAggregateInputType
  _max?: QuestionAnswerMaxAggregateInputType
}

export type QuestionAnswerGroupByOutputType = {
  id: string
  questionId: string
  submissionId: string
  selectedOptionId: string | null
  isCorrect: boolean
  _count: QuestionAnswerCountAggregateOutputType | null
  _min: QuestionAnswerMinAggregateOutputType | null
  _max: QuestionAnswerMaxAggregateOutputType | null
}

type GetQuestionAnswerGroupByPayload<T extends QuestionAnswerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuestionAnswerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuestionAnswerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuestionAnswerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuestionAnswerGroupByOutputType[P]>
      }
    >
  >



export type QuestionAnswerWhereInput = {
  AND?: Prisma.QuestionAnswerWhereInput | Prisma.QuestionAnswerWhereInput[]
  OR?: Prisma.QuestionAnswerWhereInput[]
  NOT?: Prisma.QuestionAnswerWhereInput | Prisma.QuestionAnswerWhereInput[]
  id?: Prisma.StringFilter<"QuestionAnswer"> | string
  questionId?: Prisma.StringFilter<"QuestionAnswer"> | string
  submissionId?: Prisma.StringFilter<"QuestionAnswer"> | string
  selectedOptionId?: Prisma.StringNullableFilter<"QuestionAnswer"> | string | null
  isCorrect?: Prisma.BoolFilter<"QuestionAnswer"> | boolean
  question?: Prisma.XOR<Prisma.QuestionScalarRelationFilter, Prisma.QuestionWhereInput>
  submission?: Prisma.XOR<Prisma.QuizSubmissionScalarRelationFilter, Prisma.QuizSubmissionWhereInput>
}

export type QuestionAnswerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  selectedOptionId?: Prisma.SortOrderInput | Prisma.SortOrder
  isCorrect?: Prisma.SortOrder
  question?: Prisma.QuestionOrderByWithRelationInput
  submission?: Prisma.QuizSubmissionOrderByWithRelationInput
}

export type QuestionAnswerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.QuestionAnswerWhereInput | Prisma.QuestionAnswerWhereInput[]
  OR?: Prisma.QuestionAnswerWhereInput[]
  NOT?: Prisma.QuestionAnswerWhereInput | Prisma.QuestionAnswerWhereInput[]
  questionId?: Prisma.StringFilter<"QuestionAnswer"> | string
  submissionId?: Prisma.StringFilter<"QuestionAnswer"> | string
  selectedOptionId?: Prisma.StringNullableFilter<"QuestionAnswer"> | string | null
  isCorrect?: Prisma.BoolFilter<"QuestionAnswer"> | boolean
  question?: Prisma.XOR<Prisma.QuestionScalarRelationFilter, Prisma.QuestionWhereInput>
  submission?: Prisma.XOR<Prisma.QuizSubmissionScalarRelationFilter, Prisma.QuizSubmissionWhereInput>
}, "id">

export type QuestionAnswerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  selectedOptionId?: Prisma.SortOrderInput | Prisma.SortOrder
  isCorrect?: Prisma.SortOrder
  _count?: Prisma.QuestionAnswerCountOrderByAggregateInput
  _max?: Prisma.QuestionAnswerMaxOrderByAggregateInput
  _min?: Prisma.QuestionAnswerMinOrderByAggregateInput
}

export type QuestionAnswerScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuestionAnswerScalarWhereWithAggregatesInput | Prisma.QuestionAnswerScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuestionAnswerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuestionAnswerScalarWhereWithAggregatesInput | Prisma.QuestionAnswerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"QuestionAnswer"> | string
  questionId?: Prisma.StringWithAggregatesFilter<"QuestionAnswer"> | string
  submissionId?: Prisma.StringWithAggregatesFilter<"QuestionAnswer"> | string
  selectedOptionId?: Prisma.StringNullableWithAggregatesFilter<"QuestionAnswer"> | string | null
  isCorrect?: Prisma.BoolWithAggregatesFilter<"QuestionAnswer"> | boolean
}

export type QuestionAnswerCreateInput = {
  id?: string
  selectedOptionId?: string | null
  isCorrect?: boolean
  question: Prisma.QuestionCreateNestedOneWithoutAnswersInput
  submission: Prisma.QuizSubmissionCreateNestedOneWithoutAnswersInput
}

export type QuestionAnswerUncheckedCreateInput = {
  id?: string
  questionId: string
  submissionId: string
  selectedOptionId?: string | null
  isCorrect?: boolean
}

export type QuestionAnswerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  selectedOptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  question?: Prisma.QuestionUpdateOneRequiredWithoutAnswersNestedInput
  submission?: Prisma.QuizSubmissionUpdateOneRequiredWithoutAnswersNestedInput
}

export type QuestionAnswerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  submissionId?: Prisma.StringFieldUpdateOperationsInput | string
  selectedOptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type QuestionAnswerCreateManyInput = {
  id?: string
  questionId: string
  submissionId: string
  selectedOptionId?: string | null
  isCorrect?: boolean
}

export type QuestionAnswerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  selectedOptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type QuestionAnswerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  submissionId?: Prisma.StringFieldUpdateOperationsInput | string
  selectedOptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type QuestionAnswerListRelationFilter = {
  every?: Prisma.QuestionAnswerWhereInput
  some?: Prisma.QuestionAnswerWhereInput
  none?: Prisma.QuestionAnswerWhereInput
}

export type QuestionAnswerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QuestionAnswerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  selectedOptionId?: Prisma.SortOrder
  isCorrect?: Prisma.SortOrder
}

export type QuestionAnswerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  selectedOptionId?: Prisma.SortOrder
  isCorrect?: Prisma.SortOrder
}

export type QuestionAnswerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  selectedOptionId?: Prisma.SortOrder
  isCorrect?: Prisma.SortOrder
}

export type QuestionAnswerCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.QuestionAnswerCreateWithoutQuestionInput, Prisma.QuestionAnswerUncheckedCreateWithoutQuestionInput> | Prisma.QuestionAnswerCreateWithoutQuestionInput[] | Prisma.QuestionAnswerUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuestionAnswerCreateOrConnectWithoutQuestionInput | Prisma.QuestionAnswerCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.QuestionAnswerCreateManyQuestionInputEnvelope
  connect?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
}

export type QuestionAnswerUncheckedCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.QuestionAnswerCreateWithoutQuestionInput, Prisma.QuestionAnswerUncheckedCreateWithoutQuestionInput> | Prisma.QuestionAnswerCreateWithoutQuestionInput[] | Prisma.QuestionAnswerUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuestionAnswerCreateOrConnectWithoutQuestionInput | Prisma.QuestionAnswerCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.QuestionAnswerCreateManyQuestionInputEnvelope
  connect?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
}

export type QuestionAnswerUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionAnswerCreateWithoutQuestionInput, Prisma.QuestionAnswerUncheckedCreateWithoutQuestionInput> | Prisma.QuestionAnswerCreateWithoutQuestionInput[] | Prisma.QuestionAnswerUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuestionAnswerCreateOrConnectWithoutQuestionInput | Prisma.QuestionAnswerCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.QuestionAnswerUpsertWithWhereUniqueWithoutQuestionInput | Prisma.QuestionAnswerUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.QuestionAnswerCreateManyQuestionInputEnvelope
  set?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  disconnect?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  delete?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  connect?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  update?: Prisma.QuestionAnswerUpdateWithWhereUniqueWithoutQuestionInput | Prisma.QuestionAnswerUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.QuestionAnswerUpdateManyWithWhereWithoutQuestionInput | Prisma.QuestionAnswerUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.QuestionAnswerScalarWhereInput | Prisma.QuestionAnswerScalarWhereInput[]
}

export type QuestionAnswerUncheckedUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionAnswerCreateWithoutQuestionInput, Prisma.QuestionAnswerUncheckedCreateWithoutQuestionInput> | Prisma.QuestionAnswerCreateWithoutQuestionInput[] | Prisma.QuestionAnswerUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuestionAnswerCreateOrConnectWithoutQuestionInput | Prisma.QuestionAnswerCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.QuestionAnswerUpsertWithWhereUniqueWithoutQuestionInput | Prisma.QuestionAnswerUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.QuestionAnswerCreateManyQuestionInputEnvelope
  set?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  disconnect?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  delete?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  connect?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  update?: Prisma.QuestionAnswerUpdateWithWhereUniqueWithoutQuestionInput | Prisma.QuestionAnswerUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.QuestionAnswerUpdateManyWithWhereWithoutQuestionInput | Prisma.QuestionAnswerUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.QuestionAnswerScalarWhereInput | Prisma.QuestionAnswerScalarWhereInput[]
}

export type QuestionAnswerCreateNestedManyWithoutSubmissionInput = {
  create?: Prisma.XOR<Prisma.QuestionAnswerCreateWithoutSubmissionInput, Prisma.QuestionAnswerUncheckedCreateWithoutSubmissionInput> | Prisma.QuestionAnswerCreateWithoutSubmissionInput[] | Prisma.QuestionAnswerUncheckedCreateWithoutSubmissionInput[]
  connectOrCreate?: Prisma.QuestionAnswerCreateOrConnectWithoutSubmissionInput | Prisma.QuestionAnswerCreateOrConnectWithoutSubmissionInput[]
  createMany?: Prisma.QuestionAnswerCreateManySubmissionInputEnvelope
  connect?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
}

export type QuestionAnswerUncheckedCreateNestedManyWithoutSubmissionInput = {
  create?: Prisma.XOR<Prisma.QuestionAnswerCreateWithoutSubmissionInput, Prisma.QuestionAnswerUncheckedCreateWithoutSubmissionInput> | Prisma.QuestionAnswerCreateWithoutSubmissionInput[] | Prisma.QuestionAnswerUncheckedCreateWithoutSubmissionInput[]
  connectOrCreate?: Prisma.QuestionAnswerCreateOrConnectWithoutSubmissionInput | Prisma.QuestionAnswerCreateOrConnectWithoutSubmissionInput[]
  createMany?: Prisma.QuestionAnswerCreateManySubmissionInputEnvelope
  connect?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
}

export type QuestionAnswerUpdateManyWithoutSubmissionNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionAnswerCreateWithoutSubmissionInput, Prisma.QuestionAnswerUncheckedCreateWithoutSubmissionInput> | Prisma.QuestionAnswerCreateWithoutSubmissionInput[] | Prisma.QuestionAnswerUncheckedCreateWithoutSubmissionInput[]
  connectOrCreate?: Prisma.QuestionAnswerCreateOrConnectWithoutSubmissionInput | Prisma.QuestionAnswerCreateOrConnectWithoutSubmissionInput[]
  upsert?: Prisma.QuestionAnswerUpsertWithWhereUniqueWithoutSubmissionInput | Prisma.QuestionAnswerUpsertWithWhereUniqueWithoutSubmissionInput[]
  createMany?: Prisma.QuestionAnswerCreateManySubmissionInputEnvelope
  set?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  disconnect?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  delete?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  connect?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  update?: Prisma.QuestionAnswerUpdateWithWhereUniqueWithoutSubmissionInput | Prisma.QuestionAnswerUpdateWithWhereUniqueWithoutSubmissionInput[]
  updateMany?: Prisma.QuestionAnswerUpdateManyWithWhereWithoutSubmissionInput | Prisma.QuestionAnswerUpdateManyWithWhereWithoutSubmissionInput[]
  deleteMany?: Prisma.QuestionAnswerScalarWhereInput | Prisma.QuestionAnswerScalarWhereInput[]
}

export type QuestionAnswerUncheckedUpdateManyWithoutSubmissionNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionAnswerCreateWithoutSubmissionInput, Prisma.QuestionAnswerUncheckedCreateWithoutSubmissionInput> | Prisma.QuestionAnswerCreateWithoutSubmissionInput[] | Prisma.QuestionAnswerUncheckedCreateWithoutSubmissionInput[]
  connectOrCreate?: Prisma.QuestionAnswerCreateOrConnectWithoutSubmissionInput | Prisma.QuestionAnswerCreateOrConnectWithoutSubmissionInput[]
  upsert?: Prisma.QuestionAnswerUpsertWithWhereUniqueWithoutSubmissionInput | Prisma.QuestionAnswerUpsertWithWhereUniqueWithoutSubmissionInput[]
  createMany?: Prisma.QuestionAnswerCreateManySubmissionInputEnvelope
  set?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  disconnect?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  delete?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  connect?: Prisma.QuestionAnswerWhereUniqueInput | Prisma.QuestionAnswerWhereUniqueInput[]
  update?: Prisma.QuestionAnswerUpdateWithWhereUniqueWithoutSubmissionInput | Prisma.QuestionAnswerUpdateWithWhereUniqueWithoutSubmissionInput[]
  updateMany?: Prisma.QuestionAnswerUpdateManyWithWhereWithoutSubmissionInput | Prisma.QuestionAnswerUpdateManyWithWhereWithoutSubmissionInput[]
  deleteMany?: Prisma.QuestionAnswerScalarWhereInput | Prisma.QuestionAnswerScalarWhereInput[]
}

export type QuestionAnswerCreateWithoutQuestionInput = {
  id?: string
  selectedOptionId?: string | null
  isCorrect?: boolean
  submission: Prisma.QuizSubmissionCreateNestedOneWithoutAnswersInput
}

export type QuestionAnswerUncheckedCreateWithoutQuestionInput = {
  id?: string
  submissionId: string
  selectedOptionId?: string | null
  isCorrect?: boolean
}

export type QuestionAnswerCreateOrConnectWithoutQuestionInput = {
  where: Prisma.QuestionAnswerWhereUniqueInput
  create: Prisma.XOR<Prisma.QuestionAnswerCreateWithoutQuestionInput, Prisma.QuestionAnswerUncheckedCreateWithoutQuestionInput>
}

export type QuestionAnswerCreateManyQuestionInputEnvelope = {
  data: Prisma.QuestionAnswerCreateManyQuestionInput | Prisma.QuestionAnswerCreateManyQuestionInput[]
}

export type QuestionAnswerUpsertWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.QuestionAnswerWhereUniqueInput
  update: Prisma.XOR<Prisma.QuestionAnswerUpdateWithoutQuestionInput, Prisma.QuestionAnswerUncheckedUpdateWithoutQuestionInput>
  create: Prisma.XOR<Prisma.QuestionAnswerCreateWithoutQuestionInput, Prisma.QuestionAnswerUncheckedCreateWithoutQuestionInput>
}

export type QuestionAnswerUpdateWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.QuestionAnswerWhereUniqueInput
  data: Prisma.XOR<Prisma.QuestionAnswerUpdateWithoutQuestionInput, Prisma.QuestionAnswerUncheckedUpdateWithoutQuestionInput>
}

export type QuestionAnswerUpdateManyWithWhereWithoutQuestionInput = {
  where: Prisma.QuestionAnswerScalarWhereInput
  data: Prisma.XOR<Prisma.QuestionAnswerUpdateManyMutationInput, Prisma.QuestionAnswerUncheckedUpdateManyWithoutQuestionInput>
}

export type QuestionAnswerScalarWhereInput = {
  AND?: Prisma.QuestionAnswerScalarWhereInput | Prisma.QuestionAnswerScalarWhereInput[]
  OR?: Prisma.QuestionAnswerScalarWhereInput[]
  NOT?: Prisma.QuestionAnswerScalarWhereInput | Prisma.QuestionAnswerScalarWhereInput[]
  id?: Prisma.StringFilter<"QuestionAnswer"> | string
  questionId?: Prisma.StringFilter<"QuestionAnswer"> | string
  submissionId?: Prisma.StringFilter<"QuestionAnswer"> | string
  selectedOptionId?: Prisma.StringNullableFilter<"QuestionAnswer"> | string | null
  isCorrect?: Prisma.BoolFilter<"QuestionAnswer"> | boolean
}

export type QuestionAnswerCreateWithoutSubmissionInput = {
  id?: string
  selectedOptionId?: string | null
  isCorrect?: boolean
  question: Prisma.QuestionCreateNestedOneWithoutAnswersInput
}

export type QuestionAnswerUncheckedCreateWithoutSubmissionInput = {
  id?: string
  questionId: string
  selectedOptionId?: string | null
  isCorrect?: boolean
}

export type QuestionAnswerCreateOrConnectWithoutSubmissionInput = {
  where: Prisma.QuestionAnswerWhereUniqueInput
  create: Prisma.XOR<Prisma.QuestionAnswerCreateWithoutSubmissionInput, Prisma.QuestionAnswerUncheckedCreateWithoutSubmissionInput>
}

export type QuestionAnswerCreateManySubmissionInputEnvelope = {
  data: Prisma.QuestionAnswerCreateManySubmissionInput | Prisma.QuestionAnswerCreateManySubmissionInput[]
}

export type QuestionAnswerUpsertWithWhereUniqueWithoutSubmissionInput = {
  where: Prisma.QuestionAnswerWhereUniqueInput
  update: Prisma.XOR<Prisma.QuestionAnswerUpdateWithoutSubmissionInput, Prisma.QuestionAnswerUncheckedUpdateWithoutSubmissionInput>
  create: Prisma.XOR<Prisma.QuestionAnswerCreateWithoutSubmissionInput, Prisma.QuestionAnswerUncheckedCreateWithoutSubmissionInput>
}

export type QuestionAnswerUpdateWithWhereUniqueWithoutSubmissionInput = {
  where: Prisma.QuestionAnswerWhereUniqueInput
  data: Prisma.XOR<Prisma.QuestionAnswerUpdateWithoutSubmissionInput, Prisma.QuestionAnswerUncheckedUpdateWithoutSubmissionInput>
}

export type QuestionAnswerUpdateManyWithWhereWithoutSubmissionInput = {
  where: Prisma.QuestionAnswerScalarWhereInput
  data: Prisma.XOR<Prisma.QuestionAnswerUpdateManyMutationInput, Prisma.QuestionAnswerUncheckedUpdateManyWithoutSubmissionInput>
}

export type QuestionAnswerCreateManyQuestionInput = {
  id?: string
  submissionId: string
  selectedOptionId?: string | null
  isCorrect?: boolean
}

export type QuestionAnswerUpdateWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  selectedOptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  submission?: Prisma.QuizSubmissionUpdateOneRequiredWithoutAnswersNestedInput
}

export type QuestionAnswerUncheckedUpdateWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  submissionId?: Prisma.StringFieldUpdateOperationsInput | string
  selectedOptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type QuestionAnswerUncheckedUpdateManyWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  submissionId?: Prisma.StringFieldUpdateOperationsInput | string
  selectedOptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type QuestionAnswerCreateManySubmissionInput = {
  id?: string
  questionId: string
  selectedOptionId?: string | null
  isCorrect?: boolean
}

export type QuestionAnswerUpdateWithoutSubmissionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  selectedOptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  question?: Prisma.QuestionUpdateOneRequiredWithoutAnswersNestedInput
}

export type QuestionAnswerUncheckedUpdateWithoutSubmissionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  selectedOptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type QuestionAnswerUncheckedUpdateManyWithoutSubmissionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  selectedOptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type QuestionAnswerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionId?: boolean
  submissionId?: boolean
  selectedOptionId?: boolean
  isCorrect?: boolean
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
  submission?: boolean | Prisma.QuizSubmissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionAnswer"]>

export type QuestionAnswerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionId?: boolean
  submissionId?: boolean
  selectedOptionId?: boolean
  isCorrect?: boolean
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
  submission?: boolean | Prisma.QuizSubmissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionAnswer"]>

export type QuestionAnswerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionId?: boolean
  submissionId?: boolean
  selectedOptionId?: boolean
  isCorrect?: boolean
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
  submission?: boolean | Prisma.QuizSubmissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionAnswer"]>

export type QuestionAnswerSelectScalar = {
  id?: boolean
  questionId?: boolean
  submissionId?: boolean
  selectedOptionId?: boolean
  isCorrect?: boolean
}

export type QuestionAnswerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "questionId" | "submissionId" | "selectedOptionId" | "isCorrect", ExtArgs["result"]["questionAnswer"]>
export type QuestionAnswerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
  submission?: boolean | Prisma.QuizSubmissionDefaultArgs<ExtArgs>
}
export type QuestionAnswerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
  submission?: boolean | Prisma.QuizSubmissionDefaultArgs<ExtArgs>
}
export type QuestionAnswerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
  submission?: boolean | Prisma.QuizSubmissionDefaultArgs<ExtArgs>
}

export type $QuestionAnswerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuestionAnswer"
  objects: {
    question: Prisma.$QuestionPayload<ExtArgs>
    submission: Prisma.$QuizSubmissionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    questionId: string
    submissionId: string
    selectedOptionId: string | null
    isCorrect: boolean
  }, ExtArgs["result"]["questionAnswer"]>
  composites: {}
}

export type QuestionAnswerGetPayload<S extends boolean | null | undefined | QuestionAnswerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuestionAnswerPayload, S>

export type QuestionAnswerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuestionAnswerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuestionAnswerCountAggregateInputType | true
  }

export interface QuestionAnswerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuestionAnswer'], meta: { name: 'QuestionAnswer' } }
  /**
   * Find zero or one QuestionAnswer that matches the filter.
   * @param {QuestionAnswerFindUniqueArgs} args - Arguments to find a QuestionAnswer
   * @example
   * // Get one QuestionAnswer
   * const questionAnswer = await prisma.questionAnswer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuestionAnswerFindUniqueArgs>(args: Prisma.SelectSubset<T, QuestionAnswerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuestionAnswerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuestionAnswer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuestionAnswerFindUniqueOrThrowArgs} args - Arguments to find a QuestionAnswer
   * @example
   * // Get one QuestionAnswer
   * const questionAnswer = await prisma.questionAnswer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuestionAnswerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuestionAnswerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuestionAnswerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuestionAnswer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionAnswerFindFirstArgs} args - Arguments to find a QuestionAnswer
   * @example
   * // Get one QuestionAnswer
   * const questionAnswer = await prisma.questionAnswer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuestionAnswerFindFirstArgs>(args?: Prisma.SelectSubset<T, QuestionAnswerFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuestionAnswerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuestionAnswer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionAnswerFindFirstOrThrowArgs} args - Arguments to find a QuestionAnswer
   * @example
   * // Get one QuestionAnswer
   * const questionAnswer = await prisma.questionAnswer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuestionAnswerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuestionAnswerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuestionAnswerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuestionAnswers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionAnswerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuestionAnswers
   * const questionAnswers = await prisma.questionAnswer.findMany()
   * 
   * // Get first 10 QuestionAnswers
   * const questionAnswers = await prisma.questionAnswer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const questionAnswerWithIdOnly = await prisma.questionAnswer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QuestionAnswerFindManyArgs>(args?: Prisma.SelectSubset<T, QuestionAnswerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionAnswerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuestionAnswer.
   * @param {QuestionAnswerCreateArgs} args - Arguments to create a QuestionAnswer.
   * @example
   * // Create one QuestionAnswer
   * const QuestionAnswer = await prisma.questionAnswer.create({
   *   data: {
   *     // ... data to create a QuestionAnswer
   *   }
   * })
   * 
   */
  create<T extends QuestionAnswerCreateArgs>(args: Prisma.SelectSubset<T, QuestionAnswerCreateArgs<ExtArgs>>): Prisma.Prisma__QuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuestionAnswerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuestionAnswers.
   * @param {QuestionAnswerCreateManyArgs} args - Arguments to create many QuestionAnswers.
   * @example
   * // Create many QuestionAnswers
   * const questionAnswer = await prisma.questionAnswer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuestionAnswerCreateManyArgs>(args?: Prisma.SelectSubset<T, QuestionAnswerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuestionAnswers and returns the data saved in the database.
   * @param {QuestionAnswerCreateManyAndReturnArgs} args - Arguments to create many QuestionAnswers.
   * @example
   * // Create many QuestionAnswers
   * const questionAnswer = await prisma.questionAnswer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuestionAnswers and only return the `id`
   * const questionAnswerWithIdOnly = await prisma.questionAnswer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuestionAnswerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuestionAnswerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionAnswerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuestionAnswer.
   * @param {QuestionAnswerDeleteArgs} args - Arguments to delete one QuestionAnswer.
   * @example
   * // Delete one QuestionAnswer
   * const QuestionAnswer = await prisma.questionAnswer.delete({
   *   where: {
   *     // ... filter to delete one QuestionAnswer
   *   }
   * })
   * 
   */
  delete<T extends QuestionAnswerDeleteArgs>(args: Prisma.SelectSubset<T, QuestionAnswerDeleteArgs<ExtArgs>>): Prisma.Prisma__QuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuestionAnswerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuestionAnswer.
   * @param {QuestionAnswerUpdateArgs} args - Arguments to update one QuestionAnswer.
   * @example
   * // Update one QuestionAnswer
   * const questionAnswer = await prisma.questionAnswer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuestionAnswerUpdateArgs>(args: Prisma.SelectSubset<T, QuestionAnswerUpdateArgs<ExtArgs>>): Prisma.Prisma__QuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuestionAnswerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuestionAnswers.
   * @param {QuestionAnswerDeleteManyArgs} args - Arguments to filter QuestionAnswers to delete.
   * @example
   * // Delete a few QuestionAnswers
   * const { count } = await prisma.questionAnswer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuestionAnswerDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuestionAnswerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuestionAnswers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionAnswerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuestionAnswers
   * const questionAnswer = await prisma.questionAnswer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuestionAnswerUpdateManyArgs>(args: Prisma.SelectSubset<T, QuestionAnswerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuestionAnswers and returns the data updated in the database.
   * @param {QuestionAnswerUpdateManyAndReturnArgs} args - Arguments to update many QuestionAnswers.
   * @example
   * // Update many QuestionAnswers
   * const questionAnswer = await prisma.questionAnswer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuestionAnswers and only return the `id`
   * const questionAnswerWithIdOnly = await prisma.questionAnswer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuestionAnswerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuestionAnswerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionAnswerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuestionAnswer.
   * @param {QuestionAnswerUpsertArgs} args - Arguments to update or create a QuestionAnswer.
   * @example
   * // Update or create a QuestionAnswer
   * const questionAnswer = await prisma.questionAnswer.upsert({
   *   create: {
   *     // ... data to create a QuestionAnswer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuestionAnswer we want to update
   *   }
   * })
   */
  upsert<T extends QuestionAnswerUpsertArgs>(args: Prisma.SelectSubset<T, QuestionAnswerUpsertArgs<ExtArgs>>): Prisma.Prisma__QuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuestionAnswerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuestionAnswers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionAnswerCountArgs} args - Arguments to filter QuestionAnswers to count.
   * @example
   * // Count the number of QuestionAnswers
   * const count = await prisma.questionAnswer.count({
   *   where: {
   *     // ... the filter for the QuestionAnswers we want to count
   *   }
   * })
  **/
  count<T extends QuestionAnswerCountArgs>(
    args?: Prisma.Subset<T, QuestionAnswerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuestionAnswerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuestionAnswer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionAnswerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuestionAnswerAggregateArgs>(args: Prisma.Subset<T, QuestionAnswerAggregateArgs>): Prisma.PrismaPromise<GetQuestionAnswerAggregateType<T>>

  /**
   * Group by QuestionAnswer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionAnswerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuestionAnswerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuestionAnswerGroupByArgs['orderBy'] }
      : { orderBy?: QuestionAnswerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuestionAnswerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuestionAnswerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuestionAnswer model
 */
readonly fields: QuestionAnswerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuestionAnswer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuestionAnswerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  question<T extends Prisma.QuestionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuestionDefaultArgs<ExtArgs>>): Prisma.Prisma__QuestionClient<runtime.Types.Result.GetResult<Prisma.$QuestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  submission<T extends Prisma.QuizSubmissionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuizSubmissionDefaultArgs<ExtArgs>>): Prisma.Prisma__QuizSubmissionClient<runtime.Types.Result.GetResult<Prisma.$QuizSubmissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuestionAnswer model
 */
export interface QuestionAnswerFieldRefs {
  readonly id: Prisma.FieldRef<"QuestionAnswer", 'String'>
  readonly questionId: Prisma.FieldRef<"QuestionAnswer", 'String'>
  readonly submissionId: Prisma.FieldRef<"QuestionAnswer", 'String'>
  readonly selectedOptionId: Prisma.FieldRef<"QuestionAnswer", 'String'>
  readonly isCorrect: Prisma.FieldRef<"QuestionAnswer", 'Boolean'>
}
    

// Custom InputTypes
/**
 * QuestionAnswer findUnique
 */
export type QuestionAnswerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionAnswer
   */
  select?: Prisma.QuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionAnswer
   */
  omit?: Prisma.QuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionAnswerInclude<ExtArgs> | null
  /**
   * Filter, which QuestionAnswer to fetch.
   */
  where: Prisma.QuestionAnswerWhereUniqueInput
}

/**
 * QuestionAnswer findUniqueOrThrow
 */
export type QuestionAnswerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionAnswer
   */
  select?: Prisma.QuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionAnswer
   */
  omit?: Prisma.QuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionAnswerInclude<ExtArgs> | null
  /**
   * Filter, which QuestionAnswer to fetch.
   */
  where: Prisma.QuestionAnswerWhereUniqueInput
}

/**
 * QuestionAnswer findFirst
 */
export type QuestionAnswerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionAnswer
   */
  select?: Prisma.QuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionAnswer
   */
  omit?: Prisma.QuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionAnswerInclude<ExtArgs> | null
  /**
   * Filter, which QuestionAnswer to fetch.
   */
  where?: Prisma.QuestionAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionAnswers to fetch.
   */
  orderBy?: Prisma.QuestionAnswerOrderByWithRelationInput | Prisma.QuestionAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuestionAnswers.
   */
  cursor?: Prisma.QuestionAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionAnswers.
   */
  distinct?: Prisma.QuestionAnswerScalarFieldEnum | Prisma.QuestionAnswerScalarFieldEnum[]
}

/**
 * QuestionAnswer findFirstOrThrow
 */
export type QuestionAnswerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionAnswer
   */
  select?: Prisma.QuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionAnswer
   */
  omit?: Prisma.QuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionAnswerInclude<ExtArgs> | null
  /**
   * Filter, which QuestionAnswer to fetch.
   */
  where?: Prisma.QuestionAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionAnswers to fetch.
   */
  orderBy?: Prisma.QuestionAnswerOrderByWithRelationInput | Prisma.QuestionAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuestionAnswers.
   */
  cursor?: Prisma.QuestionAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionAnswers.
   */
  distinct?: Prisma.QuestionAnswerScalarFieldEnum | Prisma.QuestionAnswerScalarFieldEnum[]
}

/**
 * QuestionAnswer findMany
 */
export type QuestionAnswerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionAnswer
   */
  select?: Prisma.QuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionAnswer
   */
  omit?: Prisma.QuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionAnswerInclude<ExtArgs> | null
  /**
   * Filter, which QuestionAnswers to fetch.
   */
  where?: Prisma.QuestionAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionAnswers to fetch.
   */
  orderBy?: Prisma.QuestionAnswerOrderByWithRelationInput | Prisma.QuestionAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuestionAnswers.
   */
  cursor?: Prisma.QuestionAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionAnswers.
   */
  skip?: number
  distinct?: Prisma.QuestionAnswerScalarFieldEnum | Prisma.QuestionAnswerScalarFieldEnum[]
}

/**
 * QuestionAnswer create
 */
export type QuestionAnswerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionAnswer
   */
  select?: Prisma.QuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionAnswer
   */
  omit?: Prisma.QuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionAnswerInclude<ExtArgs> | null
  /**
   * The data needed to create a QuestionAnswer.
   */
  data: Prisma.XOR<Prisma.QuestionAnswerCreateInput, Prisma.QuestionAnswerUncheckedCreateInput>
}

/**
 * QuestionAnswer createMany
 */
export type QuestionAnswerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuestionAnswers.
   */
  data: Prisma.QuestionAnswerCreateManyInput | Prisma.QuestionAnswerCreateManyInput[]
}

/**
 * QuestionAnswer createManyAndReturn
 */
export type QuestionAnswerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionAnswer
   */
  select?: Prisma.QuestionAnswerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionAnswer
   */
  omit?: Prisma.QuestionAnswerOmit<ExtArgs> | null
  /**
   * The data used to create many QuestionAnswers.
   */
  data: Prisma.QuestionAnswerCreateManyInput | Prisma.QuestionAnswerCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionAnswerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QuestionAnswer update
 */
export type QuestionAnswerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionAnswer
   */
  select?: Prisma.QuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionAnswer
   */
  omit?: Prisma.QuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionAnswerInclude<ExtArgs> | null
  /**
   * The data needed to update a QuestionAnswer.
   */
  data: Prisma.XOR<Prisma.QuestionAnswerUpdateInput, Prisma.QuestionAnswerUncheckedUpdateInput>
  /**
   * Choose, which QuestionAnswer to update.
   */
  where: Prisma.QuestionAnswerWhereUniqueInput
}

/**
 * QuestionAnswer updateMany
 */
export type QuestionAnswerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuestionAnswers.
   */
  data: Prisma.XOR<Prisma.QuestionAnswerUpdateManyMutationInput, Prisma.QuestionAnswerUncheckedUpdateManyInput>
  /**
   * Filter which QuestionAnswers to update
   */
  where?: Prisma.QuestionAnswerWhereInput
  /**
   * Limit how many QuestionAnswers to update.
   */
  limit?: number
}

/**
 * QuestionAnswer updateManyAndReturn
 */
export type QuestionAnswerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionAnswer
   */
  select?: Prisma.QuestionAnswerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionAnswer
   */
  omit?: Prisma.QuestionAnswerOmit<ExtArgs> | null
  /**
   * The data used to update QuestionAnswers.
   */
  data: Prisma.XOR<Prisma.QuestionAnswerUpdateManyMutationInput, Prisma.QuestionAnswerUncheckedUpdateManyInput>
  /**
   * Filter which QuestionAnswers to update
   */
  where?: Prisma.QuestionAnswerWhereInput
  /**
   * Limit how many QuestionAnswers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionAnswerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QuestionAnswer upsert
 */
export type QuestionAnswerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionAnswer
   */
  select?: Prisma.QuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionAnswer
   */
  omit?: Prisma.QuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionAnswerInclude<ExtArgs> | null
  /**
   * The filter to search for the QuestionAnswer to update in case it exists.
   */
  where: Prisma.QuestionAnswerWhereUniqueInput
  /**
   * In case the QuestionAnswer found by the `where` argument doesn't exist, create a new QuestionAnswer with this data.
   */
  create: Prisma.XOR<Prisma.QuestionAnswerCreateInput, Prisma.QuestionAnswerUncheckedCreateInput>
  /**
   * In case the QuestionAnswer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuestionAnswerUpdateInput, Prisma.QuestionAnswerUncheckedUpdateInput>
}

/**
 * QuestionAnswer delete
 */
export type QuestionAnswerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionAnswer
   */
  select?: Prisma.QuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionAnswer
   */
  omit?: Prisma.QuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionAnswerInclude<ExtArgs> | null
  /**
   * Filter which QuestionAnswer to delete.
   */
  where: Prisma.QuestionAnswerWhereUniqueInput
}

/**
 * QuestionAnswer deleteMany
 */
export type QuestionAnswerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuestionAnswers to delete
   */
  where?: Prisma.QuestionAnswerWhereInput
  /**
   * Limit how many QuestionAnswers to delete.
   */
  limit?: number
}

/**
 * QuestionAnswer without action
 */
export type QuestionAnswerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionAnswer
   */
  select?: Prisma.QuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionAnswer
   */
  omit?: Prisma.QuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionAnswerInclude<ExtArgs> | null
}
