
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QuizSubmission` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model QuizSubmission
 * 
 */
export type QuizSubmissionModel = runtime.Types.Result.DefaultSelection<Prisma.$QuizSubmissionPayload>

export type AggregateQuizSubmission = {
  _count: QuizSubmissionCountAggregateOutputType | null
  _avg: QuizSubmissionAvgAggregateOutputType | null
  _sum: QuizSubmissionSumAggregateOutputType | null
  _min: QuizSubmissionMinAggregateOutputType | null
  _max: QuizSubmissionMaxAggregateOutputType | null
}

export type QuizSubmissionAvgAggregateOutputType = {
  score: number | null
  maxScore: number | null
  percentage: number | null
  timeSpent: number | null
}

export type QuizSubmissionSumAggregateOutputType = {
  score: number | null
  maxScore: number | null
  percentage: number | null
  timeSpent: number | null
}

export type QuizSubmissionMinAggregateOutputType = {
  id: string | null
  userId: string | null
  quizId: string | null
  score: number | null
  maxScore: number | null
  percentage: number | null
  passed: boolean | null
  timeSpent: number | null
  submittedAt: Date | null
  updatedAt: Date | null
}

export type QuizSubmissionMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  quizId: string | null
  score: number | null
  maxScore: number | null
  percentage: number | null
  passed: boolean | null
  timeSpent: number | null
  submittedAt: Date | null
  updatedAt: Date | null
}

export type QuizSubmissionCountAggregateOutputType = {
  id: number
  userId: number
  quizId: number
  score: number
  maxScore: number
  percentage: number
  passed: number
  timeSpent: number
  submittedAt: number
  updatedAt: number
  _all: number
}


export type QuizSubmissionAvgAggregateInputType = {
  score?: true
  maxScore?: true
  percentage?: true
  timeSpent?: true
}

export type QuizSubmissionSumAggregateInputType = {
  score?: true
  maxScore?: true
  percentage?: true
  timeSpent?: true
}

export type QuizSubmissionMinAggregateInputType = {
  id?: true
  userId?: true
  quizId?: true
  score?: true
  maxScore?: true
  percentage?: true
  passed?: true
  timeSpent?: true
  submittedAt?: true
  updatedAt?: true
}

export type QuizSubmissionMaxAggregateInputType = {
  id?: true
  userId?: true
  quizId?: true
  score?: true
  maxScore?: true
  percentage?: true
  passed?: true
  timeSpent?: true
  submittedAt?: true
  updatedAt?: true
}

export type QuizSubmissionCountAggregateInputType = {
  id?: true
  userId?: true
  quizId?: true
  score?: true
  maxScore?: true
  percentage?: true
  passed?: true
  timeSpent?: true
  submittedAt?: true
  updatedAt?: true
  _all?: true
}

export type QuizSubmissionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuizSubmission to aggregate.
   */
  where?: Prisma.QuizSubmissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizSubmissions to fetch.
   */
  orderBy?: Prisma.QuizSubmissionOrderByWithRelationInput | Prisma.QuizSubmissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuizSubmissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizSubmissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizSubmissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuizSubmissions
  **/
  _count?: true | QuizSubmissionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: QuizSubmissionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: QuizSubmissionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuizSubmissionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuizSubmissionMaxAggregateInputType
}

export type GetQuizSubmissionAggregateType<T extends QuizSubmissionAggregateArgs> = {
      [P in keyof T & keyof AggregateQuizSubmission]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuizSubmission[P]>
    : Prisma.GetScalarType<T[P], AggregateQuizSubmission[P]>
}




export type QuizSubmissionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuizSubmissionWhereInput
  orderBy?: Prisma.QuizSubmissionOrderByWithAggregationInput | Prisma.QuizSubmissionOrderByWithAggregationInput[]
  by: Prisma.QuizSubmissionScalarFieldEnum[] | Prisma.QuizSubmissionScalarFieldEnum
  having?: Prisma.QuizSubmissionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuizSubmissionCountAggregateInputType | true
  _avg?: QuizSubmissionAvgAggregateInputType
  _sum?: QuizSubmissionSumAggregateInputType
  _min?: QuizSubmissionMinAggregateInputType
  _max?: QuizSubmissionMaxAggregateInputType
}

export type QuizSubmissionGroupByOutputType = {
  id: string
  userId: string
  quizId: string
  score: number | null
  maxScore: number | null
  percentage: number | null
  passed: boolean
  timeSpent: number | null
  submittedAt: Date
  updatedAt: Date
  _count: QuizSubmissionCountAggregateOutputType | null
  _avg: QuizSubmissionAvgAggregateOutputType | null
  _sum: QuizSubmissionSumAggregateOutputType | null
  _min: QuizSubmissionMinAggregateOutputType | null
  _max: QuizSubmissionMaxAggregateOutputType | null
}

type GetQuizSubmissionGroupByPayload<T extends QuizSubmissionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuizSubmissionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuizSubmissionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuizSubmissionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuizSubmissionGroupByOutputType[P]>
      }
    >
  >



export type QuizSubmissionWhereInput = {
  AND?: Prisma.QuizSubmissionWhereInput | Prisma.QuizSubmissionWhereInput[]
  OR?: Prisma.QuizSubmissionWhereInput[]
  NOT?: Prisma.QuizSubmissionWhereInput | Prisma.QuizSubmissionWhereInput[]
  id?: Prisma.StringFilter<"QuizSubmission"> | string
  userId?: Prisma.StringFilter<"QuizSubmission"> | string
  quizId?: Prisma.StringFilter<"QuizSubmission"> | string
  score?: Prisma.IntNullableFilter<"QuizSubmission"> | number | null
  maxScore?: Prisma.IntNullableFilter<"QuizSubmission"> | number | null
  percentage?: Prisma.FloatNullableFilter<"QuizSubmission"> | number | null
  passed?: Prisma.BoolFilter<"QuizSubmission"> | boolean
  timeSpent?: Prisma.IntNullableFilter<"QuizSubmission"> | number | null
  submittedAt?: Prisma.DateTimeFilter<"QuizSubmission"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuizSubmission"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  quiz?: Prisma.XOR<Prisma.QuizScalarRelationFilter, Prisma.QuizWhereInput>
  answers?: Prisma.QuestionAnswerListRelationFilter
}

export type QuizSubmissionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  quizId?: Prisma.SortOrder
  score?: Prisma.SortOrderInput | Prisma.SortOrder
  maxScore?: Prisma.SortOrderInput | Prisma.SortOrder
  percentage?: Prisma.SortOrderInput | Prisma.SortOrder
  passed?: Prisma.SortOrder
  timeSpent?: Prisma.SortOrderInput | Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  quiz?: Prisma.QuizOrderByWithRelationInput
  answers?: Prisma.QuestionAnswerOrderByRelationAggregateInput
}

export type QuizSubmissionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.QuizSubmissionWhereInput | Prisma.QuizSubmissionWhereInput[]
  OR?: Prisma.QuizSubmissionWhereInput[]
  NOT?: Prisma.QuizSubmissionWhereInput | Prisma.QuizSubmissionWhereInput[]
  userId?: Prisma.StringFilter<"QuizSubmission"> | string
  quizId?: Prisma.StringFilter<"QuizSubmission"> | string
  score?: Prisma.IntNullableFilter<"QuizSubmission"> | number | null
  maxScore?: Prisma.IntNullableFilter<"QuizSubmission"> | number | null
  percentage?: Prisma.FloatNullableFilter<"QuizSubmission"> | number | null
  passed?: Prisma.BoolFilter<"QuizSubmission"> | boolean
  timeSpent?: Prisma.IntNullableFilter<"QuizSubmission"> | number | null
  submittedAt?: Prisma.DateTimeFilter<"QuizSubmission"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuizSubmission"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  quiz?: Prisma.XOR<Prisma.QuizScalarRelationFilter, Prisma.QuizWhereInput>
  answers?: Prisma.QuestionAnswerListRelationFilter
}, "id">

export type QuizSubmissionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  quizId?: Prisma.SortOrder
  score?: Prisma.SortOrderInput | Prisma.SortOrder
  maxScore?: Prisma.SortOrderInput | Prisma.SortOrder
  percentage?: Prisma.SortOrderInput | Prisma.SortOrder
  passed?: Prisma.SortOrder
  timeSpent?: Prisma.SortOrderInput | Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.QuizSubmissionCountOrderByAggregateInput
  _avg?: Prisma.QuizSubmissionAvgOrderByAggregateInput
  _max?: Prisma.QuizSubmissionMaxOrderByAggregateInput
  _min?: Prisma.QuizSubmissionMinOrderByAggregateInput
  _sum?: Prisma.QuizSubmissionSumOrderByAggregateInput
}

export type QuizSubmissionScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuizSubmissionScalarWhereWithAggregatesInput | Prisma.QuizSubmissionScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuizSubmissionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuizSubmissionScalarWhereWithAggregatesInput | Prisma.QuizSubmissionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"QuizSubmission"> | string
  userId?: Prisma.StringWithAggregatesFilter<"QuizSubmission"> | string
  quizId?: Prisma.StringWithAggregatesFilter<"QuizSubmission"> | string
  score?: Prisma.IntNullableWithAggregatesFilter<"QuizSubmission"> | number | null
  maxScore?: Prisma.IntNullableWithAggregatesFilter<"QuizSubmission"> | number | null
  percentage?: Prisma.FloatNullableWithAggregatesFilter<"QuizSubmission"> | number | null
  passed?: Prisma.BoolWithAggregatesFilter<"QuizSubmission"> | boolean
  timeSpent?: Prisma.IntNullableWithAggregatesFilter<"QuizSubmission"> | number | null
  submittedAt?: Prisma.DateTimeWithAggregatesFilter<"QuizSubmission"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"QuizSubmission"> | Date | string
}

export type QuizSubmissionCreateInput = {
  id?: string
  score?: number | null
  maxScore?: number | null
  percentage?: number | null
  passed?: boolean
  timeSpent?: number | null
  submittedAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSubmissionsInput
  quiz: Prisma.QuizCreateNestedOneWithoutSubmissionsInput
  answers?: Prisma.QuestionAnswerCreateNestedManyWithoutSubmissionInput
}

export type QuizSubmissionUncheckedCreateInput = {
  id?: string
  userId: string
  quizId: string
  score?: number | null
  maxScore?: number | null
  percentage?: number | null
  passed?: boolean
  timeSpent?: number | null
  submittedAt?: Date | string
  updatedAt?: Date | string
  answers?: Prisma.QuestionAnswerUncheckedCreateNestedManyWithoutSubmissionInput
}

export type QuizSubmissionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  percentage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  timeSpent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSubmissionsNestedInput
  quiz?: Prisma.QuizUpdateOneRequiredWithoutSubmissionsNestedInput
  answers?: Prisma.QuestionAnswerUpdateManyWithoutSubmissionNestedInput
}

export type QuizSubmissionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  quizId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  percentage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  timeSpent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  answers?: Prisma.QuestionAnswerUncheckedUpdateManyWithoutSubmissionNestedInput
}

export type QuizSubmissionCreateManyInput = {
  id?: string
  userId: string
  quizId: string
  score?: number | null
  maxScore?: number | null
  percentage?: number | null
  passed?: boolean
  timeSpent?: number | null
  submittedAt?: Date | string
  updatedAt?: Date | string
}

export type QuizSubmissionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  percentage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  timeSpent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizSubmissionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  quizId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  percentage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  timeSpent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizSubmissionListRelationFilter = {
  every?: Prisma.QuizSubmissionWhereInput
  some?: Prisma.QuizSubmissionWhereInput
  none?: Prisma.QuizSubmissionWhereInput
}

export type QuizSubmissionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QuizSubmissionScalarRelationFilter = {
  is?: Prisma.QuizSubmissionWhereInput
  isNot?: Prisma.QuizSubmissionWhereInput
}

export type QuizSubmissionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  quizId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  maxScore?: Prisma.SortOrder
  percentage?: Prisma.SortOrder
  passed?: Prisma.SortOrder
  timeSpent?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuizSubmissionAvgOrderByAggregateInput = {
  score?: Prisma.SortOrder
  maxScore?: Prisma.SortOrder
  percentage?: Prisma.SortOrder
  timeSpent?: Prisma.SortOrder
}

export type QuizSubmissionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  quizId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  maxScore?: Prisma.SortOrder
  percentage?: Prisma.SortOrder
  passed?: Prisma.SortOrder
  timeSpent?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuizSubmissionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  quizId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  maxScore?: Prisma.SortOrder
  percentage?: Prisma.SortOrder
  passed?: Prisma.SortOrder
  timeSpent?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuizSubmissionSumOrderByAggregateInput = {
  score?: Prisma.SortOrder
  maxScore?: Prisma.SortOrder
  percentage?: Prisma.SortOrder
  timeSpent?: Prisma.SortOrder
}

export type QuizSubmissionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutUserInput, Prisma.QuizSubmissionUncheckedCreateWithoutUserInput> | Prisma.QuizSubmissionCreateWithoutUserInput[] | Prisma.QuizSubmissionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuizSubmissionCreateOrConnectWithoutUserInput | Prisma.QuizSubmissionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.QuizSubmissionCreateManyUserInputEnvelope
  connect?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
}

export type QuizSubmissionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutUserInput, Prisma.QuizSubmissionUncheckedCreateWithoutUserInput> | Prisma.QuizSubmissionCreateWithoutUserInput[] | Prisma.QuizSubmissionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuizSubmissionCreateOrConnectWithoutUserInput | Prisma.QuizSubmissionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.QuizSubmissionCreateManyUserInputEnvelope
  connect?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
}

export type QuizSubmissionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutUserInput, Prisma.QuizSubmissionUncheckedCreateWithoutUserInput> | Prisma.QuizSubmissionCreateWithoutUserInput[] | Prisma.QuizSubmissionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuizSubmissionCreateOrConnectWithoutUserInput | Prisma.QuizSubmissionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.QuizSubmissionUpsertWithWhereUniqueWithoutUserInput | Prisma.QuizSubmissionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.QuizSubmissionCreateManyUserInputEnvelope
  set?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  disconnect?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  delete?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  connect?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  update?: Prisma.QuizSubmissionUpdateWithWhereUniqueWithoutUserInput | Prisma.QuizSubmissionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.QuizSubmissionUpdateManyWithWhereWithoutUserInput | Prisma.QuizSubmissionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.QuizSubmissionScalarWhereInput | Prisma.QuizSubmissionScalarWhereInput[]
}

export type QuizSubmissionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutUserInput, Prisma.QuizSubmissionUncheckedCreateWithoutUserInput> | Prisma.QuizSubmissionCreateWithoutUserInput[] | Prisma.QuizSubmissionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuizSubmissionCreateOrConnectWithoutUserInput | Prisma.QuizSubmissionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.QuizSubmissionUpsertWithWhereUniqueWithoutUserInput | Prisma.QuizSubmissionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.QuizSubmissionCreateManyUserInputEnvelope
  set?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  disconnect?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  delete?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  connect?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  update?: Prisma.QuizSubmissionUpdateWithWhereUniqueWithoutUserInput | Prisma.QuizSubmissionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.QuizSubmissionUpdateManyWithWhereWithoutUserInput | Prisma.QuizSubmissionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.QuizSubmissionScalarWhereInput | Prisma.QuizSubmissionScalarWhereInput[]
}

export type QuizSubmissionCreateNestedManyWithoutQuizInput = {
  create?: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutQuizInput, Prisma.QuizSubmissionUncheckedCreateWithoutQuizInput> | Prisma.QuizSubmissionCreateWithoutQuizInput[] | Prisma.QuizSubmissionUncheckedCreateWithoutQuizInput[]
  connectOrCreate?: Prisma.QuizSubmissionCreateOrConnectWithoutQuizInput | Prisma.QuizSubmissionCreateOrConnectWithoutQuizInput[]
  createMany?: Prisma.QuizSubmissionCreateManyQuizInputEnvelope
  connect?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
}

export type QuizSubmissionUncheckedCreateNestedManyWithoutQuizInput = {
  create?: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutQuizInput, Prisma.QuizSubmissionUncheckedCreateWithoutQuizInput> | Prisma.QuizSubmissionCreateWithoutQuizInput[] | Prisma.QuizSubmissionUncheckedCreateWithoutQuizInput[]
  connectOrCreate?: Prisma.QuizSubmissionCreateOrConnectWithoutQuizInput | Prisma.QuizSubmissionCreateOrConnectWithoutQuizInput[]
  createMany?: Prisma.QuizSubmissionCreateManyQuizInputEnvelope
  connect?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
}

export type QuizSubmissionUpdateManyWithoutQuizNestedInput = {
  create?: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutQuizInput, Prisma.QuizSubmissionUncheckedCreateWithoutQuizInput> | Prisma.QuizSubmissionCreateWithoutQuizInput[] | Prisma.QuizSubmissionUncheckedCreateWithoutQuizInput[]
  connectOrCreate?: Prisma.QuizSubmissionCreateOrConnectWithoutQuizInput | Prisma.QuizSubmissionCreateOrConnectWithoutQuizInput[]
  upsert?: Prisma.QuizSubmissionUpsertWithWhereUniqueWithoutQuizInput | Prisma.QuizSubmissionUpsertWithWhereUniqueWithoutQuizInput[]
  createMany?: Prisma.QuizSubmissionCreateManyQuizInputEnvelope
  set?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  disconnect?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  delete?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  connect?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  update?: Prisma.QuizSubmissionUpdateWithWhereUniqueWithoutQuizInput | Prisma.QuizSubmissionUpdateWithWhereUniqueWithoutQuizInput[]
  updateMany?: Prisma.QuizSubmissionUpdateManyWithWhereWithoutQuizInput | Prisma.QuizSubmissionUpdateManyWithWhereWithoutQuizInput[]
  deleteMany?: Prisma.QuizSubmissionScalarWhereInput | Prisma.QuizSubmissionScalarWhereInput[]
}

export type QuizSubmissionUncheckedUpdateManyWithoutQuizNestedInput = {
  create?: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutQuizInput, Prisma.QuizSubmissionUncheckedCreateWithoutQuizInput> | Prisma.QuizSubmissionCreateWithoutQuizInput[] | Prisma.QuizSubmissionUncheckedCreateWithoutQuizInput[]
  connectOrCreate?: Prisma.QuizSubmissionCreateOrConnectWithoutQuizInput | Prisma.QuizSubmissionCreateOrConnectWithoutQuizInput[]
  upsert?: Prisma.QuizSubmissionUpsertWithWhereUniqueWithoutQuizInput | Prisma.QuizSubmissionUpsertWithWhereUniqueWithoutQuizInput[]
  createMany?: Prisma.QuizSubmissionCreateManyQuizInputEnvelope
  set?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  disconnect?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  delete?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  connect?: Prisma.QuizSubmissionWhereUniqueInput | Prisma.QuizSubmissionWhereUniqueInput[]
  update?: Prisma.QuizSubmissionUpdateWithWhereUniqueWithoutQuizInput | Prisma.QuizSubmissionUpdateWithWhereUniqueWithoutQuizInput[]
  updateMany?: Prisma.QuizSubmissionUpdateManyWithWhereWithoutQuizInput | Prisma.QuizSubmissionUpdateManyWithWhereWithoutQuizInput[]
  deleteMany?: Prisma.QuizSubmissionScalarWhereInput | Prisma.QuizSubmissionScalarWhereInput[]
}

export type QuizSubmissionCreateNestedOneWithoutAnswersInput = {
  create?: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutAnswersInput, Prisma.QuizSubmissionUncheckedCreateWithoutAnswersInput>
  connectOrCreate?: Prisma.QuizSubmissionCreateOrConnectWithoutAnswersInput
  connect?: Prisma.QuizSubmissionWhereUniqueInput
}

export type QuizSubmissionUpdateOneRequiredWithoutAnswersNestedInput = {
  create?: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutAnswersInput, Prisma.QuizSubmissionUncheckedCreateWithoutAnswersInput>
  connectOrCreate?: Prisma.QuizSubmissionCreateOrConnectWithoutAnswersInput
  upsert?: Prisma.QuizSubmissionUpsertWithoutAnswersInput
  connect?: Prisma.QuizSubmissionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.QuizSubmissionUpdateToOneWithWhereWithoutAnswersInput, Prisma.QuizSubmissionUpdateWithoutAnswersInput>, Prisma.QuizSubmissionUncheckedUpdateWithoutAnswersInput>
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type QuizSubmissionCreateWithoutUserInput = {
  id?: string
  score?: number | null
  maxScore?: number | null
  percentage?: number | null
  passed?: boolean
  timeSpent?: number | null
  submittedAt?: Date | string
  updatedAt?: Date | string
  quiz: Prisma.QuizCreateNestedOneWithoutSubmissionsInput
  answers?: Prisma.QuestionAnswerCreateNestedManyWithoutSubmissionInput
}

export type QuizSubmissionUncheckedCreateWithoutUserInput = {
  id?: string
  quizId: string
  score?: number | null
  maxScore?: number | null
  percentage?: number | null
  passed?: boolean
  timeSpent?: number | null
  submittedAt?: Date | string
  updatedAt?: Date | string
  answers?: Prisma.QuestionAnswerUncheckedCreateNestedManyWithoutSubmissionInput
}

export type QuizSubmissionCreateOrConnectWithoutUserInput = {
  where: Prisma.QuizSubmissionWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutUserInput, Prisma.QuizSubmissionUncheckedCreateWithoutUserInput>
}

export type QuizSubmissionCreateManyUserInputEnvelope = {
  data: Prisma.QuizSubmissionCreateManyUserInput | Prisma.QuizSubmissionCreateManyUserInput[]
}

export type QuizSubmissionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.QuizSubmissionWhereUniqueInput
  update: Prisma.XOR<Prisma.QuizSubmissionUpdateWithoutUserInput, Prisma.QuizSubmissionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutUserInput, Prisma.QuizSubmissionUncheckedCreateWithoutUserInput>
}

export type QuizSubmissionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.QuizSubmissionWhereUniqueInput
  data: Prisma.XOR<Prisma.QuizSubmissionUpdateWithoutUserInput, Prisma.QuizSubmissionUncheckedUpdateWithoutUserInput>
}

export type QuizSubmissionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.QuizSubmissionScalarWhereInput
  data: Prisma.XOR<Prisma.QuizSubmissionUpdateManyMutationInput, Prisma.QuizSubmissionUncheckedUpdateManyWithoutUserInput>
}

export type QuizSubmissionScalarWhereInput = {
  AND?: Prisma.QuizSubmissionScalarWhereInput | Prisma.QuizSubmissionScalarWhereInput[]
  OR?: Prisma.QuizSubmissionScalarWhereInput[]
  NOT?: Prisma.QuizSubmissionScalarWhereInput | Prisma.QuizSubmissionScalarWhereInput[]
  id?: Prisma.StringFilter<"QuizSubmission"> | string
  userId?: Prisma.StringFilter<"QuizSubmission"> | string
  quizId?: Prisma.StringFilter<"QuizSubmission"> | string
  score?: Prisma.IntNullableFilter<"QuizSubmission"> | number | null
  maxScore?: Prisma.IntNullableFilter<"QuizSubmission"> | number | null
  percentage?: Prisma.FloatNullableFilter<"QuizSubmission"> | number | null
  passed?: Prisma.BoolFilter<"QuizSubmission"> | boolean
  timeSpent?: Prisma.IntNullableFilter<"QuizSubmission"> | number | null
  submittedAt?: Prisma.DateTimeFilter<"QuizSubmission"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuizSubmission"> | Date | string
}

export type QuizSubmissionCreateWithoutQuizInput = {
  id?: string
  score?: number | null
  maxScore?: number | null
  percentage?: number | null
  passed?: boolean
  timeSpent?: number | null
  submittedAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSubmissionsInput
  answers?: Prisma.QuestionAnswerCreateNestedManyWithoutSubmissionInput
}

export type QuizSubmissionUncheckedCreateWithoutQuizInput = {
  id?: string
  userId: string
  score?: number | null
  maxScore?: number | null
  percentage?: number | null
  passed?: boolean
  timeSpent?: number | null
  submittedAt?: Date | string
  updatedAt?: Date | string
  answers?: Prisma.QuestionAnswerUncheckedCreateNestedManyWithoutSubmissionInput
}

export type QuizSubmissionCreateOrConnectWithoutQuizInput = {
  where: Prisma.QuizSubmissionWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutQuizInput, Prisma.QuizSubmissionUncheckedCreateWithoutQuizInput>
}

export type QuizSubmissionCreateManyQuizInputEnvelope = {
  data: Prisma.QuizSubmissionCreateManyQuizInput | Prisma.QuizSubmissionCreateManyQuizInput[]
}

export type QuizSubmissionUpsertWithWhereUniqueWithoutQuizInput = {
  where: Prisma.QuizSubmissionWhereUniqueInput
  update: Prisma.XOR<Prisma.QuizSubmissionUpdateWithoutQuizInput, Prisma.QuizSubmissionUncheckedUpdateWithoutQuizInput>
  create: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutQuizInput, Prisma.QuizSubmissionUncheckedCreateWithoutQuizInput>
}

export type QuizSubmissionUpdateWithWhereUniqueWithoutQuizInput = {
  where: Prisma.QuizSubmissionWhereUniqueInput
  data: Prisma.XOR<Prisma.QuizSubmissionUpdateWithoutQuizInput, Prisma.QuizSubmissionUncheckedUpdateWithoutQuizInput>
}

export type QuizSubmissionUpdateManyWithWhereWithoutQuizInput = {
  where: Prisma.QuizSubmissionScalarWhereInput
  data: Prisma.XOR<Prisma.QuizSubmissionUpdateManyMutationInput, Prisma.QuizSubmissionUncheckedUpdateManyWithoutQuizInput>
}

export type QuizSubmissionCreateWithoutAnswersInput = {
  id?: string
  score?: number | null
  maxScore?: number | null
  percentage?: number | null
  passed?: boolean
  timeSpent?: number | null
  submittedAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSubmissionsInput
  quiz: Prisma.QuizCreateNestedOneWithoutSubmissionsInput
}

export type QuizSubmissionUncheckedCreateWithoutAnswersInput = {
  id?: string
  userId: string
  quizId: string
  score?: number | null
  maxScore?: number | null
  percentage?: number | null
  passed?: boolean
  timeSpent?: number | null
  submittedAt?: Date | string
  updatedAt?: Date | string
}

export type QuizSubmissionCreateOrConnectWithoutAnswersInput = {
  where: Prisma.QuizSubmissionWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutAnswersInput, Prisma.QuizSubmissionUncheckedCreateWithoutAnswersInput>
}

export type QuizSubmissionUpsertWithoutAnswersInput = {
  update: Prisma.XOR<Prisma.QuizSubmissionUpdateWithoutAnswersInput, Prisma.QuizSubmissionUncheckedUpdateWithoutAnswersInput>
  create: Prisma.XOR<Prisma.QuizSubmissionCreateWithoutAnswersInput, Prisma.QuizSubmissionUncheckedCreateWithoutAnswersInput>
  where?: Prisma.QuizSubmissionWhereInput
}

export type QuizSubmissionUpdateToOneWithWhereWithoutAnswersInput = {
  where?: Prisma.QuizSubmissionWhereInput
  data: Prisma.XOR<Prisma.QuizSubmissionUpdateWithoutAnswersInput, Prisma.QuizSubmissionUncheckedUpdateWithoutAnswersInput>
}

export type QuizSubmissionUpdateWithoutAnswersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  percentage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  timeSpent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSubmissionsNestedInput
  quiz?: Prisma.QuizUpdateOneRequiredWithoutSubmissionsNestedInput
}

export type QuizSubmissionUncheckedUpdateWithoutAnswersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  quizId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  percentage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  timeSpent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizSubmissionCreateManyUserInput = {
  id?: string
  quizId: string
  score?: number | null
  maxScore?: number | null
  percentage?: number | null
  passed?: boolean
  timeSpent?: number | null
  submittedAt?: Date | string
  updatedAt?: Date | string
}

export type QuizSubmissionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  percentage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  timeSpent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quiz?: Prisma.QuizUpdateOneRequiredWithoutSubmissionsNestedInput
  answers?: Prisma.QuestionAnswerUpdateManyWithoutSubmissionNestedInput
}

export type QuizSubmissionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quizId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  percentage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  timeSpent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  answers?: Prisma.QuestionAnswerUncheckedUpdateManyWithoutSubmissionNestedInput
}

export type QuizSubmissionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quizId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  percentage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  timeSpent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizSubmissionCreateManyQuizInput = {
  id?: string
  userId: string
  score?: number | null
  maxScore?: number | null
  percentage?: number | null
  passed?: boolean
  timeSpent?: number | null
  submittedAt?: Date | string
  updatedAt?: Date | string
}

export type QuizSubmissionUpdateWithoutQuizInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  percentage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  timeSpent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSubmissionsNestedInput
  answers?: Prisma.QuestionAnswerUpdateManyWithoutSubmissionNestedInput
}

export type QuizSubmissionUncheckedUpdateWithoutQuizInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  percentage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  timeSpent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  answers?: Prisma.QuestionAnswerUncheckedUpdateManyWithoutSubmissionNestedInput
}

export type QuizSubmissionUncheckedUpdateManyWithoutQuizInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  percentage?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  timeSpent?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  submittedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type QuizSubmissionCountOutputType
 */

export type QuizSubmissionCountOutputType = {
  answers: number
}

export type QuizSubmissionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  answers?: boolean | QuizSubmissionCountOutputTypeCountAnswersArgs
}

/**
 * QuizSubmissionCountOutputType without action
 */
export type QuizSubmissionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSubmissionCountOutputType
   */
  select?: Prisma.QuizSubmissionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * QuizSubmissionCountOutputType without action
 */
export type QuizSubmissionCountOutputTypeCountAnswersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuestionAnswerWhereInput
}


export type QuizSubmissionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  quizId?: boolean
  score?: boolean
  maxScore?: boolean
  percentage?: boolean
  passed?: boolean
  timeSpent?: boolean
  submittedAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  quiz?: boolean | Prisma.QuizDefaultArgs<ExtArgs>
  answers?: boolean | Prisma.QuizSubmission$answersArgs<ExtArgs>
  _count?: boolean | Prisma.QuizSubmissionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizSubmission"]>

export type QuizSubmissionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  quizId?: boolean
  score?: boolean
  maxScore?: boolean
  percentage?: boolean
  passed?: boolean
  timeSpent?: boolean
  submittedAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  quiz?: boolean | Prisma.QuizDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizSubmission"]>

export type QuizSubmissionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  quizId?: boolean
  score?: boolean
  maxScore?: boolean
  percentage?: boolean
  passed?: boolean
  timeSpent?: boolean
  submittedAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  quiz?: boolean | Prisma.QuizDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizSubmission"]>

export type QuizSubmissionSelectScalar = {
  id?: boolean
  userId?: boolean
  quizId?: boolean
  score?: boolean
  maxScore?: boolean
  percentage?: boolean
  passed?: boolean
  timeSpent?: boolean
  submittedAt?: boolean
  updatedAt?: boolean
}

export type QuizSubmissionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "quizId" | "score" | "maxScore" | "percentage" | "passed" | "timeSpent" | "submittedAt" | "updatedAt", ExtArgs["result"]["quizSubmission"]>
export type QuizSubmissionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  quiz?: boolean | Prisma.QuizDefaultArgs<ExtArgs>
  answers?: boolean | Prisma.QuizSubmission$answersArgs<ExtArgs>
  _count?: boolean | Prisma.QuizSubmissionCountOutputTypeDefaultArgs<ExtArgs>
}
export type QuizSubmissionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  quiz?: boolean | Prisma.QuizDefaultArgs<ExtArgs>
}
export type QuizSubmissionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  quiz?: boolean | Prisma.QuizDefaultArgs<ExtArgs>
}

export type $QuizSubmissionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuizSubmission"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    quiz: Prisma.$QuizPayload<ExtArgs>
    answers: Prisma.$QuestionAnswerPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    quizId: string
    score: number | null
    maxScore: number | null
    percentage: number | null
    passed: boolean
    timeSpent: number | null
    submittedAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["quizSubmission"]>
  composites: {}
}

export type QuizSubmissionGetPayload<S extends boolean | null | undefined | QuizSubmissionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuizSubmissionPayload, S>

export type QuizSubmissionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuizSubmissionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuizSubmissionCountAggregateInputType | true
  }

export interface QuizSubmissionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuizSubmission'], meta: { name: 'QuizSubmission' } }
  /**
   * Find zero or one QuizSubmission that matches the filter.
   * @param {QuizSubmissionFindUniqueArgs} args - Arguments to find a QuizSubmission
   * @example
   * // Get one QuizSubmission
   * const quizSubmission = await prisma.quizSubmission.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuizSubmissionFindUniqueArgs>(args: Prisma.SelectSubset<T, QuizSubmissionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuizSubmissionClient<runtime.Types.Result.GetResult<Prisma.$QuizSubmissionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuizSubmission that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuizSubmissionFindUniqueOrThrowArgs} args - Arguments to find a QuizSubmission
   * @example
   * // Get one QuizSubmission
   * const quizSubmission = await prisma.quizSubmission.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuizSubmissionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuizSubmissionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuizSubmissionClient<runtime.Types.Result.GetResult<Prisma.$QuizSubmissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuizSubmission that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSubmissionFindFirstArgs} args - Arguments to find a QuizSubmission
   * @example
   * // Get one QuizSubmission
   * const quizSubmission = await prisma.quizSubmission.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuizSubmissionFindFirstArgs>(args?: Prisma.SelectSubset<T, QuizSubmissionFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuizSubmissionClient<runtime.Types.Result.GetResult<Prisma.$QuizSubmissionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuizSubmission that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSubmissionFindFirstOrThrowArgs} args - Arguments to find a QuizSubmission
   * @example
   * // Get one QuizSubmission
   * const quizSubmission = await prisma.quizSubmission.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuizSubmissionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuizSubmissionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuizSubmissionClient<runtime.Types.Result.GetResult<Prisma.$QuizSubmissionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuizSubmissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSubmissionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuizSubmissions
   * const quizSubmissions = await prisma.quizSubmission.findMany()
   * 
   * // Get first 10 QuizSubmissions
   * const quizSubmissions = await prisma.quizSubmission.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const quizSubmissionWithIdOnly = await prisma.quizSubmission.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QuizSubmissionFindManyArgs>(args?: Prisma.SelectSubset<T, QuizSubmissionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizSubmissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuizSubmission.
   * @param {QuizSubmissionCreateArgs} args - Arguments to create a QuizSubmission.
   * @example
   * // Create one QuizSubmission
   * const QuizSubmission = await prisma.quizSubmission.create({
   *   data: {
   *     // ... data to create a QuizSubmission
   *   }
   * })
   * 
   */
  create<T extends QuizSubmissionCreateArgs>(args: Prisma.SelectSubset<T, QuizSubmissionCreateArgs<ExtArgs>>): Prisma.Prisma__QuizSubmissionClient<runtime.Types.Result.GetResult<Prisma.$QuizSubmissionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuizSubmissions.
   * @param {QuizSubmissionCreateManyArgs} args - Arguments to create many QuizSubmissions.
   * @example
   * // Create many QuizSubmissions
   * const quizSubmission = await prisma.quizSubmission.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuizSubmissionCreateManyArgs>(args?: Prisma.SelectSubset<T, QuizSubmissionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuizSubmissions and returns the data saved in the database.
   * @param {QuizSubmissionCreateManyAndReturnArgs} args - Arguments to create many QuizSubmissions.
   * @example
   * // Create many QuizSubmissions
   * const quizSubmission = await prisma.quizSubmission.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuizSubmissions and only return the `id`
   * const quizSubmissionWithIdOnly = await prisma.quizSubmission.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuizSubmissionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuizSubmissionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizSubmissionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuizSubmission.
   * @param {QuizSubmissionDeleteArgs} args - Arguments to delete one QuizSubmission.
   * @example
   * // Delete one QuizSubmission
   * const QuizSubmission = await prisma.quizSubmission.delete({
   *   where: {
   *     // ... filter to delete one QuizSubmission
   *   }
   * })
   * 
   */
  delete<T extends QuizSubmissionDeleteArgs>(args: Prisma.SelectSubset<T, QuizSubmissionDeleteArgs<ExtArgs>>): Prisma.Prisma__QuizSubmissionClient<runtime.Types.Result.GetResult<Prisma.$QuizSubmissionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuizSubmission.
   * @param {QuizSubmissionUpdateArgs} args - Arguments to update one QuizSubmission.
   * @example
   * // Update one QuizSubmission
   * const quizSubmission = await prisma.quizSubmission.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuizSubmissionUpdateArgs>(args: Prisma.SelectSubset<T, QuizSubmissionUpdateArgs<ExtArgs>>): Prisma.Prisma__QuizSubmissionClient<runtime.Types.Result.GetResult<Prisma.$QuizSubmissionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuizSubmissions.
   * @param {QuizSubmissionDeleteManyArgs} args - Arguments to filter QuizSubmissions to delete.
   * @example
   * // Delete a few QuizSubmissions
   * const { count } = await prisma.quizSubmission.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuizSubmissionDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuizSubmissionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuizSubmissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSubmissionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuizSubmissions
   * const quizSubmission = await prisma.quizSubmission.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuizSubmissionUpdateManyArgs>(args: Prisma.SelectSubset<T, QuizSubmissionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuizSubmissions and returns the data updated in the database.
   * @param {QuizSubmissionUpdateManyAndReturnArgs} args - Arguments to update many QuizSubmissions.
   * @example
   * // Update many QuizSubmissions
   * const quizSubmission = await prisma.quizSubmission.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuizSubmissions and only return the `id`
   * const quizSubmissionWithIdOnly = await prisma.quizSubmission.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuizSubmissionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuizSubmissionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizSubmissionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuizSubmission.
   * @param {QuizSubmissionUpsertArgs} args - Arguments to update or create a QuizSubmission.
   * @example
   * // Update or create a QuizSubmission
   * const quizSubmission = await prisma.quizSubmission.upsert({
   *   create: {
   *     // ... data to create a QuizSubmission
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuizSubmission we want to update
   *   }
   * })
   */
  upsert<T extends QuizSubmissionUpsertArgs>(args: Prisma.SelectSubset<T, QuizSubmissionUpsertArgs<ExtArgs>>): Prisma.Prisma__QuizSubmissionClient<runtime.Types.Result.GetResult<Prisma.$QuizSubmissionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuizSubmissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSubmissionCountArgs} args - Arguments to filter QuizSubmissions to count.
   * @example
   * // Count the number of QuizSubmissions
   * const count = await prisma.quizSubmission.count({
   *   where: {
   *     // ... the filter for the QuizSubmissions we want to count
   *   }
   * })
  **/
  count<T extends QuizSubmissionCountArgs>(
    args?: Prisma.Subset<T, QuizSubmissionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuizSubmissionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuizSubmission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSubmissionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuizSubmissionAggregateArgs>(args: Prisma.Subset<T, QuizSubmissionAggregateArgs>): Prisma.PrismaPromise<GetQuizSubmissionAggregateType<T>>

  /**
   * Group by QuizSubmission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSubmissionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuizSubmissionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuizSubmissionGroupByArgs['orderBy'] }
      : { orderBy?: QuizSubmissionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuizSubmissionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuizSubmissionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuizSubmission model
 */
readonly fields: QuizSubmissionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuizSubmission.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuizSubmissionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  quiz<T extends Prisma.QuizDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuizDefaultArgs<ExtArgs>>): Prisma.Prisma__QuizClient<runtime.Types.Result.GetResult<Prisma.$QuizPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  answers<T extends Prisma.QuizSubmission$answersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuizSubmission$answersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionAnswerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuizSubmission model
 */
export interface QuizSubmissionFieldRefs {
  readonly id: Prisma.FieldRef<"QuizSubmission", 'String'>
  readonly userId: Prisma.FieldRef<"QuizSubmission", 'String'>
  readonly quizId: Prisma.FieldRef<"QuizSubmission", 'String'>
  readonly score: Prisma.FieldRef<"QuizSubmission", 'Int'>
  readonly maxScore: Prisma.FieldRef<"QuizSubmission", 'Int'>
  readonly percentage: Prisma.FieldRef<"QuizSubmission", 'Float'>
  readonly passed: Prisma.FieldRef<"QuizSubmission", 'Boolean'>
  readonly timeSpent: Prisma.FieldRef<"QuizSubmission", 'Int'>
  readonly submittedAt: Prisma.FieldRef<"QuizSubmission", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"QuizSubmission", 'DateTime'>
}
    

// Custom InputTypes
/**
 * QuizSubmission findUnique
 */
export type QuizSubmissionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSubmission
   */
  select?: Prisma.QuizSubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSubmission
   */
  omit?: Prisma.QuizSubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSubmissionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSubmission to fetch.
   */
  where: Prisma.QuizSubmissionWhereUniqueInput
}

/**
 * QuizSubmission findUniqueOrThrow
 */
export type QuizSubmissionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSubmission
   */
  select?: Prisma.QuizSubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSubmission
   */
  omit?: Prisma.QuizSubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSubmissionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSubmission to fetch.
   */
  where: Prisma.QuizSubmissionWhereUniqueInput
}

/**
 * QuizSubmission findFirst
 */
export type QuizSubmissionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSubmission
   */
  select?: Prisma.QuizSubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSubmission
   */
  omit?: Prisma.QuizSubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSubmissionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSubmission to fetch.
   */
  where?: Prisma.QuizSubmissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizSubmissions to fetch.
   */
  orderBy?: Prisma.QuizSubmissionOrderByWithRelationInput | Prisma.QuizSubmissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuizSubmissions.
   */
  cursor?: Prisma.QuizSubmissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizSubmissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizSubmissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizSubmissions.
   */
  distinct?: Prisma.QuizSubmissionScalarFieldEnum | Prisma.QuizSubmissionScalarFieldEnum[]
}

/**
 * QuizSubmission findFirstOrThrow
 */
export type QuizSubmissionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSubmission
   */
  select?: Prisma.QuizSubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSubmission
   */
  omit?: Prisma.QuizSubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSubmissionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSubmission to fetch.
   */
  where?: Prisma.QuizSubmissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizSubmissions to fetch.
   */
  orderBy?: Prisma.QuizSubmissionOrderByWithRelationInput | Prisma.QuizSubmissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuizSubmissions.
   */
  cursor?: Prisma.QuizSubmissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizSubmissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizSubmissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizSubmissions.
   */
  distinct?: Prisma.QuizSubmissionScalarFieldEnum | Prisma.QuizSubmissionScalarFieldEnum[]
}

/**
 * QuizSubmission findMany
 */
export type QuizSubmissionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSubmission
   */
  select?: Prisma.QuizSubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSubmission
   */
  omit?: Prisma.QuizSubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSubmissionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSubmissions to fetch.
   */
  where?: Prisma.QuizSubmissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizSubmissions to fetch.
   */
  orderBy?: Prisma.QuizSubmissionOrderByWithRelationInput | Prisma.QuizSubmissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuizSubmissions.
   */
  cursor?: Prisma.QuizSubmissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizSubmissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizSubmissions.
   */
  skip?: number
  distinct?: Prisma.QuizSubmissionScalarFieldEnum | Prisma.QuizSubmissionScalarFieldEnum[]
}

/**
 * QuizSubmission create
 */
export type QuizSubmissionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSubmission
   */
  select?: Prisma.QuizSubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSubmission
   */
  omit?: Prisma.QuizSubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSubmissionInclude<ExtArgs> | null
  /**
   * The data needed to create a QuizSubmission.
   */
  data: Prisma.XOR<Prisma.QuizSubmissionCreateInput, Prisma.QuizSubmissionUncheckedCreateInput>
}

/**
 * QuizSubmission createMany
 */
export type QuizSubmissionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuizSubmissions.
   */
  data: Prisma.QuizSubmissionCreateManyInput | Prisma.QuizSubmissionCreateManyInput[]
}

/**
 * QuizSubmission createManyAndReturn
 */
export type QuizSubmissionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSubmission
   */
  select?: Prisma.QuizSubmissionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSubmission
   */
  omit?: Prisma.QuizSubmissionOmit<ExtArgs> | null
  /**
   * The data used to create many QuizSubmissions.
   */
  data: Prisma.QuizSubmissionCreateManyInput | Prisma.QuizSubmissionCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSubmissionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QuizSubmission update
 */
export type QuizSubmissionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSubmission
   */
  select?: Prisma.QuizSubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSubmission
   */
  omit?: Prisma.QuizSubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSubmissionInclude<ExtArgs> | null
  /**
   * The data needed to update a QuizSubmission.
   */
  data: Prisma.XOR<Prisma.QuizSubmissionUpdateInput, Prisma.QuizSubmissionUncheckedUpdateInput>
  /**
   * Choose, which QuizSubmission to update.
   */
  where: Prisma.QuizSubmissionWhereUniqueInput
}

/**
 * QuizSubmission updateMany
 */
export type QuizSubmissionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuizSubmissions.
   */
  data: Prisma.XOR<Prisma.QuizSubmissionUpdateManyMutationInput, Prisma.QuizSubmissionUncheckedUpdateManyInput>
  /**
   * Filter which QuizSubmissions to update
   */
  where?: Prisma.QuizSubmissionWhereInput
  /**
   * Limit how many QuizSubmissions to update.
   */
  limit?: number
}

/**
 * QuizSubmission updateManyAndReturn
 */
export type QuizSubmissionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSubmission
   */
  select?: Prisma.QuizSubmissionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSubmission
   */
  omit?: Prisma.QuizSubmissionOmit<ExtArgs> | null
  /**
   * The data used to update QuizSubmissions.
   */
  data: Prisma.XOR<Prisma.QuizSubmissionUpdateManyMutationInput, Prisma.QuizSubmissionUncheckedUpdateManyInput>
  /**
   * Filter which QuizSubmissions to update
   */
  where?: Prisma.QuizSubmissionWhereInput
  /**
   * Limit how many QuizSubmissions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSubmissionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QuizSubmission upsert
 */
export type QuizSubmissionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSubmission
   */
  select?: Prisma.QuizSubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSubmission
   */
  omit?: Prisma.QuizSubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSubmissionInclude<ExtArgs> | null
  /**
   * The filter to search for the QuizSubmission to update in case it exists.
   */
  where: Prisma.QuizSubmissionWhereUniqueInput
  /**
   * In case the QuizSubmission found by the `where` argument doesn't exist, create a new QuizSubmission with this data.
   */
  create: Prisma.XOR<Prisma.QuizSubmissionCreateInput, Prisma.QuizSubmissionUncheckedCreateInput>
  /**
   * In case the QuizSubmission was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuizSubmissionUpdateInput, Prisma.QuizSubmissionUncheckedUpdateInput>
}

/**
 * QuizSubmission delete
 */
export type QuizSubmissionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSubmission
   */
  select?: Prisma.QuizSubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSubmission
   */
  omit?: Prisma.QuizSubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSubmissionInclude<ExtArgs> | null
  /**
   * Filter which QuizSubmission to delete.
   */
  where: Prisma.QuizSubmissionWhereUniqueInput
}

/**
 * QuizSubmission deleteMany
 */
export type QuizSubmissionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuizSubmissions to delete
   */
  where?: Prisma.QuizSubmissionWhereInput
  /**
   * Limit how many QuizSubmissions to delete.
   */
  limit?: number
}

/**
 * QuizSubmission.answers
 */
export type QuizSubmission$answersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionAnswer
   */
  select?: Prisma.QuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionAnswer
   */
  omit?: Prisma.QuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionAnswerInclude<ExtArgs> | null
  where?: Prisma.QuestionAnswerWhereInput
  orderBy?: Prisma.QuestionAnswerOrderByWithRelationInput | Prisma.QuestionAnswerOrderByWithRelationInput[]
  cursor?: Prisma.QuestionAnswerWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.QuestionAnswerScalarFieldEnum | Prisma.QuestionAnswerScalarFieldEnum[]
}

/**
 * QuizSubmission without action
 */
export type QuizSubmissionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSubmission
   */
  select?: Prisma.QuizSubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSubmission
   */
  omit?: Prisma.QuizSubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSubmissionInclude<ExtArgs> | null
}
