
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserMinAggregateOutputType = {
  id: string | null
  email: string | null
  username: string | null
  password: string | null
  firstName: string | null
  lastName: string | null
  role: $Enums.UserRole | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserMaxAggregateOutputType = {
  id: string | null
  email: string | null
  username: string | null
  password: string | null
  firstName: string | null
  lastName: string | null
  role: $Enums.UserRole | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserCountAggregateOutputType = {
  id: number
  email: number
  username: number
  password: number
  firstName: number
  lastName: number
  role: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type UserMinAggregateInputType = {
  id?: true
  email?: true
  username?: true
  password?: true
  firstName?: true
  lastName?: true
  role?: true
  createdAt?: true
  updatedAt?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  email?: true
  username?: true
  password?: true
  firstName?: true
  lastName?: true
  role?: true
  createdAt?: true
  updatedAt?: true
}

export type UserCountAggregateInputType = {
  id?: true
  email?: true
  username?: true
  password?: true
  firstName?: true
  lastName?: true
  role?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: string
  email: string
  username: string
  password: string
  firstName: string | null
  lastName: string | null
  role: $Enums.UserRole
  createdAt: Date
  updatedAt: Date
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.StringFilter<"User"> | string
  email?: Prisma.StringFilter<"User"> | string
  username?: Prisma.StringFilter<"User"> | string
  password?: Prisma.StringFilter<"User"> | string
  firstName?: Prisma.StringNullableFilter<"User"> | string | null
  lastName?: Prisma.StringNullableFilter<"User"> | string | null
  role?: Prisma.EnumUserRoleFilter<"User"> | $Enums.UserRole
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  profile?: Prisma.XOR<Prisma.UserProfileNullableScalarRelationFilter, Prisma.UserProfileWhereInput> | null
  enrollments?: Prisma.EnrollmentListRelationFilter
  progress?: Prisma.ProgressListRelationFilter
  submissions?: Prisma.QuizSubmissionListRelationFilter
  createdPaths?: Prisma.LearningPathListRelationFilter
  createdModules?: Prisma.ModuleListRelationFilter
  createdLessons?: Prisma.LessonListRelationFilter
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  username?: Prisma.SortOrder
  password?: Prisma.SortOrder
  firstName?: Prisma.SortOrderInput | Prisma.SortOrder
  lastName?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  profile?: Prisma.UserProfileOrderByWithRelationInput
  enrollments?: Prisma.EnrollmentOrderByRelationAggregateInput
  progress?: Prisma.ProgressOrderByRelationAggregateInput
  submissions?: Prisma.QuizSubmissionOrderByRelationAggregateInput
  createdPaths?: Prisma.LearningPathOrderByRelationAggregateInput
  createdModules?: Prisma.ModuleOrderByRelationAggregateInput
  createdLessons?: Prisma.LessonOrderByRelationAggregateInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  username?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  password?: Prisma.StringFilter<"User"> | string
  firstName?: Prisma.StringNullableFilter<"User"> | string | null
  lastName?: Prisma.StringNullableFilter<"User"> | string | null
  role?: Prisma.EnumUserRoleFilter<"User"> | $Enums.UserRole
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  profile?: Prisma.XOR<Prisma.UserProfileNullableScalarRelationFilter, Prisma.UserProfileWhereInput> | null
  enrollments?: Prisma.EnrollmentListRelationFilter
  progress?: Prisma.ProgressListRelationFilter
  submissions?: Prisma.QuizSubmissionListRelationFilter
  createdPaths?: Prisma.LearningPathListRelationFilter
  createdModules?: Prisma.ModuleListRelationFilter
  createdLessons?: Prisma.LessonListRelationFilter
}, "id" | "email" | "username">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  username?: Prisma.SortOrder
  password?: Prisma.SortOrder
  firstName?: Prisma.SortOrderInput | Prisma.SortOrder
  lastName?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"User"> | string
  email?: Prisma.StringWithAggregatesFilter<"User"> | string
  username?: Prisma.StringWithAggregatesFilter<"User"> | string
  password?: Prisma.StringWithAggregatesFilter<"User"> | string
  firstName?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  lastName?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  role?: Prisma.EnumUserRoleWithAggregatesFilter<"User"> | $Enums.UserRole
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
}

export type UserCreateInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  profile?: Prisma.UserProfileCreateNestedOneWithoutUserInput
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutUserInput
  progress?: Prisma.ProgressCreateNestedManyWithoutUserInput
  submissions?: Prisma.QuizSubmissionCreateNestedManyWithoutUserInput
  createdPaths?: Prisma.LearningPathCreateNestedManyWithoutCreatorInput
  createdModules?: Prisma.ModuleCreateNestedManyWithoutCreatorInput
  createdLessons?: Prisma.LessonCreateNestedManyWithoutCreatorInput
}

export type UserUncheckedCreateInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  profile?: Prisma.UserProfileUncheckedCreateNestedOneWithoutUserInput
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutUserInput
  progress?: Prisma.ProgressUncheckedCreateNestedManyWithoutUserInput
  submissions?: Prisma.QuizSubmissionUncheckedCreateNestedManyWithoutUserInput
  createdPaths?: Prisma.LearningPathUncheckedCreateNestedManyWithoutCreatorInput
  createdModules?: Prisma.ModuleUncheckedCreateNestedManyWithoutCreatorInput
  createdLessons?: Prisma.LessonUncheckedCreateNestedManyWithoutCreatorInput
}

export type UserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.UserProfileUpdateOneWithoutUserNestedInput
  enrollments?: Prisma.EnrollmentUpdateManyWithoutUserNestedInput
  progress?: Prisma.ProgressUpdateManyWithoutUserNestedInput
  submissions?: Prisma.QuizSubmissionUpdateManyWithoutUserNestedInput
  createdPaths?: Prisma.LearningPathUpdateManyWithoutCreatorNestedInput
  createdModules?: Prisma.ModuleUpdateManyWithoutCreatorNestedInput
  createdLessons?: Prisma.LessonUpdateManyWithoutCreatorNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.UserProfileUncheckedUpdateOneWithoutUserNestedInput
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutUserNestedInput
  progress?: Prisma.ProgressUncheckedUpdateManyWithoutUserNestedInput
  submissions?: Prisma.QuizSubmissionUncheckedUpdateManyWithoutUserNestedInput
  createdPaths?: Prisma.LearningPathUncheckedUpdateManyWithoutCreatorNestedInput
  createdModules?: Prisma.ModuleUncheckedUpdateManyWithoutCreatorNestedInput
  createdLessons?: Prisma.LessonUncheckedUpdateManyWithoutCreatorNestedInput
}

export type UserCreateManyInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  username?: Prisma.SortOrder
  password?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  username?: Prisma.SortOrder
  password?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  username?: Prisma.SortOrder
  password?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type EnumUserRoleFieldUpdateOperationsInput = {
  set?: $Enums.UserRole
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type UserCreateNestedOneWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutProfileInput, Prisma.UserUncheckedCreateWithoutProfileInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutProfileInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutProfileInput, Prisma.UserUncheckedCreateWithoutProfileInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutProfileInput
  upsert?: Prisma.UserUpsertWithoutProfileInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutProfileInput, Prisma.UserUpdateWithoutProfileInput>, Prisma.UserUncheckedUpdateWithoutProfileInput>
}

export type UserCreateNestedOneWithoutCreatedPathsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCreatedPathsInput, Prisma.UserUncheckedCreateWithoutCreatedPathsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCreatedPathsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutCreatedPathsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCreatedPathsInput, Prisma.UserUncheckedCreateWithoutCreatedPathsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCreatedPathsInput
  upsert?: Prisma.UserUpsertWithoutCreatedPathsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutCreatedPathsInput, Prisma.UserUpdateWithoutCreatedPathsInput>, Prisma.UserUncheckedUpdateWithoutCreatedPathsInput>
}

export type UserCreateNestedOneWithoutCreatedModulesInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCreatedModulesInput, Prisma.UserUncheckedCreateWithoutCreatedModulesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCreatedModulesInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutCreatedModulesNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCreatedModulesInput, Prisma.UserUncheckedCreateWithoutCreatedModulesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCreatedModulesInput
  upsert?: Prisma.UserUpsertWithoutCreatedModulesInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutCreatedModulesInput, Prisma.UserUpdateWithoutCreatedModulesInput>, Prisma.UserUncheckedUpdateWithoutCreatedModulesInput>
}

export type UserCreateNestedOneWithoutCreatedLessonsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCreatedLessonsInput, Prisma.UserUncheckedCreateWithoutCreatedLessonsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCreatedLessonsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutCreatedLessonsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCreatedLessonsInput, Prisma.UserUncheckedCreateWithoutCreatedLessonsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCreatedLessonsInput
  upsert?: Prisma.UserUpsertWithoutCreatedLessonsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutCreatedLessonsInput, Prisma.UserUpdateWithoutCreatedLessonsInput>, Prisma.UserUncheckedUpdateWithoutCreatedLessonsInput>
}

export type UserCreateNestedOneWithoutSubmissionsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutSubmissionsInput, Prisma.UserUncheckedCreateWithoutSubmissionsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutSubmissionsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutSubmissionsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutSubmissionsInput, Prisma.UserUncheckedCreateWithoutSubmissionsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutSubmissionsInput
  upsert?: Prisma.UserUpsertWithoutSubmissionsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutSubmissionsInput, Prisma.UserUpdateWithoutSubmissionsInput>, Prisma.UserUncheckedUpdateWithoutSubmissionsInput>
}

export type UserCreateNestedOneWithoutEnrollmentsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutEnrollmentsInput, Prisma.UserUncheckedCreateWithoutEnrollmentsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutEnrollmentsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutEnrollmentsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutEnrollmentsInput, Prisma.UserUncheckedCreateWithoutEnrollmentsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutEnrollmentsInput
  upsert?: Prisma.UserUpsertWithoutEnrollmentsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutEnrollmentsInput, Prisma.UserUpdateWithoutEnrollmentsInput>, Prisma.UserUncheckedUpdateWithoutEnrollmentsInput>
}

export type UserCreateNestedOneWithoutProgressInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutProgressInput, Prisma.UserUncheckedCreateWithoutProgressInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutProgressInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutProgressNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutProgressInput, Prisma.UserUncheckedCreateWithoutProgressInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutProgressInput
  upsert?: Prisma.UserUpsertWithoutProgressInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutProgressInput, Prisma.UserUpdateWithoutProgressInput>, Prisma.UserUncheckedUpdateWithoutProgressInput>
}

export type UserCreateWithoutProfileInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutUserInput
  progress?: Prisma.ProgressCreateNestedManyWithoutUserInput
  submissions?: Prisma.QuizSubmissionCreateNestedManyWithoutUserInput
  createdPaths?: Prisma.LearningPathCreateNestedManyWithoutCreatorInput
  createdModules?: Prisma.ModuleCreateNestedManyWithoutCreatorInput
  createdLessons?: Prisma.LessonCreateNestedManyWithoutCreatorInput
}

export type UserUncheckedCreateWithoutProfileInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutUserInput
  progress?: Prisma.ProgressUncheckedCreateNestedManyWithoutUserInput
  submissions?: Prisma.QuizSubmissionUncheckedCreateNestedManyWithoutUserInput
  createdPaths?: Prisma.LearningPathUncheckedCreateNestedManyWithoutCreatorInput
  createdModules?: Prisma.ModuleUncheckedCreateNestedManyWithoutCreatorInput
  createdLessons?: Prisma.LessonUncheckedCreateNestedManyWithoutCreatorInput
}

export type UserCreateOrConnectWithoutProfileInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutProfileInput, Prisma.UserUncheckedCreateWithoutProfileInput>
}

export type UserUpsertWithoutProfileInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutProfileInput, Prisma.UserUncheckedUpdateWithoutProfileInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutProfileInput, Prisma.UserUncheckedCreateWithoutProfileInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutProfileInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutProfileInput, Prisma.UserUncheckedUpdateWithoutProfileInput>
}

export type UserUpdateWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  enrollments?: Prisma.EnrollmentUpdateManyWithoutUserNestedInput
  progress?: Prisma.ProgressUpdateManyWithoutUserNestedInput
  submissions?: Prisma.QuizSubmissionUpdateManyWithoutUserNestedInput
  createdPaths?: Prisma.LearningPathUpdateManyWithoutCreatorNestedInput
  createdModules?: Prisma.ModuleUpdateManyWithoutCreatorNestedInput
  createdLessons?: Prisma.LessonUpdateManyWithoutCreatorNestedInput
}

export type UserUncheckedUpdateWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutUserNestedInput
  progress?: Prisma.ProgressUncheckedUpdateManyWithoutUserNestedInput
  submissions?: Prisma.QuizSubmissionUncheckedUpdateManyWithoutUserNestedInput
  createdPaths?: Prisma.LearningPathUncheckedUpdateManyWithoutCreatorNestedInput
  createdModules?: Prisma.ModuleUncheckedUpdateManyWithoutCreatorNestedInput
  createdLessons?: Prisma.LessonUncheckedUpdateManyWithoutCreatorNestedInput
}

export type UserCreateWithoutCreatedPathsInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  profile?: Prisma.UserProfileCreateNestedOneWithoutUserInput
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutUserInput
  progress?: Prisma.ProgressCreateNestedManyWithoutUserInput
  submissions?: Prisma.QuizSubmissionCreateNestedManyWithoutUserInput
  createdModules?: Prisma.ModuleCreateNestedManyWithoutCreatorInput
  createdLessons?: Prisma.LessonCreateNestedManyWithoutCreatorInput
}

export type UserUncheckedCreateWithoutCreatedPathsInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  profile?: Prisma.UserProfileUncheckedCreateNestedOneWithoutUserInput
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutUserInput
  progress?: Prisma.ProgressUncheckedCreateNestedManyWithoutUserInput
  submissions?: Prisma.QuizSubmissionUncheckedCreateNestedManyWithoutUserInput
  createdModules?: Prisma.ModuleUncheckedCreateNestedManyWithoutCreatorInput
  createdLessons?: Prisma.LessonUncheckedCreateNestedManyWithoutCreatorInput
}

export type UserCreateOrConnectWithoutCreatedPathsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutCreatedPathsInput, Prisma.UserUncheckedCreateWithoutCreatedPathsInput>
}

export type UserUpsertWithoutCreatedPathsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutCreatedPathsInput, Prisma.UserUncheckedUpdateWithoutCreatedPathsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutCreatedPathsInput, Prisma.UserUncheckedCreateWithoutCreatedPathsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutCreatedPathsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutCreatedPathsInput, Prisma.UserUncheckedUpdateWithoutCreatedPathsInput>
}

export type UserUpdateWithoutCreatedPathsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.UserProfileUpdateOneWithoutUserNestedInput
  enrollments?: Prisma.EnrollmentUpdateManyWithoutUserNestedInput
  progress?: Prisma.ProgressUpdateManyWithoutUserNestedInput
  submissions?: Prisma.QuizSubmissionUpdateManyWithoutUserNestedInput
  createdModules?: Prisma.ModuleUpdateManyWithoutCreatorNestedInput
  createdLessons?: Prisma.LessonUpdateManyWithoutCreatorNestedInput
}

export type UserUncheckedUpdateWithoutCreatedPathsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.UserProfileUncheckedUpdateOneWithoutUserNestedInput
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutUserNestedInput
  progress?: Prisma.ProgressUncheckedUpdateManyWithoutUserNestedInput
  submissions?: Prisma.QuizSubmissionUncheckedUpdateManyWithoutUserNestedInput
  createdModules?: Prisma.ModuleUncheckedUpdateManyWithoutCreatorNestedInput
  createdLessons?: Prisma.LessonUncheckedUpdateManyWithoutCreatorNestedInput
}

export type UserCreateWithoutCreatedModulesInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  profile?: Prisma.UserProfileCreateNestedOneWithoutUserInput
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutUserInput
  progress?: Prisma.ProgressCreateNestedManyWithoutUserInput
  submissions?: Prisma.QuizSubmissionCreateNestedManyWithoutUserInput
  createdPaths?: Prisma.LearningPathCreateNestedManyWithoutCreatorInput
  createdLessons?: Prisma.LessonCreateNestedManyWithoutCreatorInput
}

export type UserUncheckedCreateWithoutCreatedModulesInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  profile?: Prisma.UserProfileUncheckedCreateNestedOneWithoutUserInput
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutUserInput
  progress?: Prisma.ProgressUncheckedCreateNestedManyWithoutUserInput
  submissions?: Prisma.QuizSubmissionUncheckedCreateNestedManyWithoutUserInput
  createdPaths?: Prisma.LearningPathUncheckedCreateNestedManyWithoutCreatorInput
  createdLessons?: Prisma.LessonUncheckedCreateNestedManyWithoutCreatorInput
}

export type UserCreateOrConnectWithoutCreatedModulesInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutCreatedModulesInput, Prisma.UserUncheckedCreateWithoutCreatedModulesInput>
}

export type UserUpsertWithoutCreatedModulesInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutCreatedModulesInput, Prisma.UserUncheckedUpdateWithoutCreatedModulesInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutCreatedModulesInput, Prisma.UserUncheckedCreateWithoutCreatedModulesInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutCreatedModulesInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutCreatedModulesInput, Prisma.UserUncheckedUpdateWithoutCreatedModulesInput>
}

export type UserUpdateWithoutCreatedModulesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.UserProfileUpdateOneWithoutUserNestedInput
  enrollments?: Prisma.EnrollmentUpdateManyWithoutUserNestedInput
  progress?: Prisma.ProgressUpdateManyWithoutUserNestedInput
  submissions?: Prisma.QuizSubmissionUpdateManyWithoutUserNestedInput
  createdPaths?: Prisma.LearningPathUpdateManyWithoutCreatorNestedInput
  createdLessons?: Prisma.LessonUpdateManyWithoutCreatorNestedInput
}

export type UserUncheckedUpdateWithoutCreatedModulesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.UserProfileUncheckedUpdateOneWithoutUserNestedInput
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutUserNestedInput
  progress?: Prisma.ProgressUncheckedUpdateManyWithoutUserNestedInput
  submissions?: Prisma.QuizSubmissionUncheckedUpdateManyWithoutUserNestedInput
  createdPaths?: Prisma.LearningPathUncheckedUpdateManyWithoutCreatorNestedInput
  createdLessons?: Prisma.LessonUncheckedUpdateManyWithoutCreatorNestedInput
}

export type UserCreateWithoutCreatedLessonsInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  profile?: Prisma.UserProfileCreateNestedOneWithoutUserInput
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutUserInput
  progress?: Prisma.ProgressCreateNestedManyWithoutUserInput
  submissions?: Prisma.QuizSubmissionCreateNestedManyWithoutUserInput
  createdPaths?: Prisma.LearningPathCreateNestedManyWithoutCreatorInput
  createdModules?: Prisma.ModuleCreateNestedManyWithoutCreatorInput
}

export type UserUncheckedCreateWithoutCreatedLessonsInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  profile?: Prisma.UserProfileUncheckedCreateNestedOneWithoutUserInput
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutUserInput
  progress?: Prisma.ProgressUncheckedCreateNestedManyWithoutUserInput
  submissions?: Prisma.QuizSubmissionUncheckedCreateNestedManyWithoutUserInput
  createdPaths?: Prisma.LearningPathUncheckedCreateNestedManyWithoutCreatorInput
  createdModules?: Prisma.ModuleUncheckedCreateNestedManyWithoutCreatorInput
}

export type UserCreateOrConnectWithoutCreatedLessonsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutCreatedLessonsInput, Prisma.UserUncheckedCreateWithoutCreatedLessonsInput>
}

export type UserUpsertWithoutCreatedLessonsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutCreatedLessonsInput, Prisma.UserUncheckedUpdateWithoutCreatedLessonsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutCreatedLessonsInput, Prisma.UserUncheckedCreateWithoutCreatedLessonsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutCreatedLessonsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutCreatedLessonsInput, Prisma.UserUncheckedUpdateWithoutCreatedLessonsInput>
}

export type UserUpdateWithoutCreatedLessonsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.UserProfileUpdateOneWithoutUserNestedInput
  enrollments?: Prisma.EnrollmentUpdateManyWithoutUserNestedInput
  progress?: Prisma.ProgressUpdateManyWithoutUserNestedInput
  submissions?: Prisma.QuizSubmissionUpdateManyWithoutUserNestedInput
  createdPaths?: Prisma.LearningPathUpdateManyWithoutCreatorNestedInput
  createdModules?: Prisma.ModuleUpdateManyWithoutCreatorNestedInput
}

export type UserUncheckedUpdateWithoutCreatedLessonsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.UserProfileUncheckedUpdateOneWithoutUserNestedInput
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutUserNestedInput
  progress?: Prisma.ProgressUncheckedUpdateManyWithoutUserNestedInput
  submissions?: Prisma.QuizSubmissionUncheckedUpdateManyWithoutUserNestedInput
  createdPaths?: Prisma.LearningPathUncheckedUpdateManyWithoutCreatorNestedInput
  createdModules?: Prisma.ModuleUncheckedUpdateManyWithoutCreatorNestedInput
}

export type UserCreateWithoutSubmissionsInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  profile?: Prisma.UserProfileCreateNestedOneWithoutUserInput
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutUserInput
  progress?: Prisma.ProgressCreateNestedManyWithoutUserInput
  createdPaths?: Prisma.LearningPathCreateNestedManyWithoutCreatorInput
  createdModules?: Prisma.ModuleCreateNestedManyWithoutCreatorInput
  createdLessons?: Prisma.LessonCreateNestedManyWithoutCreatorInput
}

export type UserUncheckedCreateWithoutSubmissionsInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  profile?: Prisma.UserProfileUncheckedCreateNestedOneWithoutUserInput
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutUserInput
  progress?: Prisma.ProgressUncheckedCreateNestedManyWithoutUserInput
  createdPaths?: Prisma.LearningPathUncheckedCreateNestedManyWithoutCreatorInput
  createdModules?: Prisma.ModuleUncheckedCreateNestedManyWithoutCreatorInput
  createdLessons?: Prisma.LessonUncheckedCreateNestedManyWithoutCreatorInput
}

export type UserCreateOrConnectWithoutSubmissionsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutSubmissionsInput, Prisma.UserUncheckedCreateWithoutSubmissionsInput>
}

export type UserUpsertWithoutSubmissionsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutSubmissionsInput, Prisma.UserUncheckedUpdateWithoutSubmissionsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutSubmissionsInput, Prisma.UserUncheckedCreateWithoutSubmissionsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutSubmissionsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutSubmissionsInput, Prisma.UserUncheckedUpdateWithoutSubmissionsInput>
}

export type UserUpdateWithoutSubmissionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.UserProfileUpdateOneWithoutUserNestedInput
  enrollments?: Prisma.EnrollmentUpdateManyWithoutUserNestedInput
  progress?: Prisma.ProgressUpdateManyWithoutUserNestedInput
  createdPaths?: Prisma.LearningPathUpdateManyWithoutCreatorNestedInput
  createdModules?: Prisma.ModuleUpdateManyWithoutCreatorNestedInput
  createdLessons?: Prisma.LessonUpdateManyWithoutCreatorNestedInput
}

export type UserUncheckedUpdateWithoutSubmissionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.UserProfileUncheckedUpdateOneWithoutUserNestedInput
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutUserNestedInput
  progress?: Prisma.ProgressUncheckedUpdateManyWithoutUserNestedInput
  createdPaths?: Prisma.LearningPathUncheckedUpdateManyWithoutCreatorNestedInput
  createdModules?: Prisma.ModuleUncheckedUpdateManyWithoutCreatorNestedInput
  createdLessons?: Prisma.LessonUncheckedUpdateManyWithoutCreatorNestedInput
}

export type UserCreateWithoutEnrollmentsInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  profile?: Prisma.UserProfileCreateNestedOneWithoutUserInput
  progress?: Prisma.ProgressCreateNestedManyWithoutUserInput
  submissions?: Prisma.QuizSubmissionCreateNestedManyWithoutUserInput
  createdPaths?: Prisma.LearningPathCreateNestedManyWithoutCreatorInput
  createdModules?: Prisma.ModuleCreateNestedManyWithoutCreatorInput
  createdLessons?: Prisma.LessonCreateNestedManyWithoutCreatorInput
}

export type UserUncheckedCreateWithoutEnrollmentsInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  profile?: Prisma.UserProfileUncheckedCreateNestedOneWithoutUserInput
  progress?: Prisma.ProgressUncheckedCreateNestedManyWithoutUserInput
  submissions?: Prisma.QuizSubmissionUncheckedCreateNestedManyWithoutUserInput
  createdPaths?: Prisma.LearningPathUncheckedCreateNestedManyWithoutCreatorInput
  createdModules?: Prisma.ModuleUncheckedCreateNestedManyWithoutCreatorInput
  createdLessons?: Prisma.LessonUncheckedCreateNestedManyWithoutCreatorInput
}

export type UserCreateOrConnectWithoutEnrollmentsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutEnrollmentsInput, Prisma.UserUncheckedCreateWithoutEnrollmentsInput>
}

export type UserUpsertWithoutEnrollmentsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutEnrollmentsInput, Prisma.UserUncheckedUpdateWithoutEnrollmentsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutEnrollmentsInput, Prisma.UserUncheckedCreateWithoutEnrollmentsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutEnrollmentsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutEnrollmentsInput, Prisma.UserUncheckedUpdateWithoutEnrollmentsInput>
}

export type UserUpdateWithoutEnrollmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.UserProfileUpdateOneWithoutUserNestedInput
  progress?: Prisma.ProgressUpdateManyWithoutUserNestedInput
  submissions?: Prisma.QuizSubmissionUpdateManyWithoutUserNestedInput
  createdPaths?: Prisma.LearningPathUpdateManyWithoutCreatorNestedInput
  createdModules?: Prisma.ModuleUpdateManyWithoutCreatorNestedInput
  createdLessons?: Prisma.LessonUpdateManyWithoutCreatorNestedInput
}

export type UserUncheckedUpdateWithoutEnrollmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.UserProfileUncheckedUpdateOneWithoutUserNestedInput
  progress?: Prisma.ProgressUncheckedUpdateManyWithoutUserNestedInput
  submissions?: Prisma.QuizSubmissionUncheckedUpdateManyWithoutUserNestedInput
  createdPaths?: Prisma.LearningPathUncheckedUpdateManyWithoutCreatorNestedInput
  createdModules?: Prisma.ModuleUncheckedUpdateManyWithoutCreatorNestedInput
  createdLessons?: Prisma.LessonUncheckedUpdateManyWithoutCreatorNestedInput
}

export type UserCreateWithoutProgressInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  profile?: Prisma.UserProfileCreateNestedOneWithoutUserInput
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutUserInput
  submissions?: Prisma.QuizSubmissionCreateNestedManyWithoutUserInput
  createdPaths?: Prisma.LearningPathCreateNestedManyWithoutCreatorInput
  createdModules?: Prisma.ModuleCreateNestedManyWithoutCreatorInput
  createdLessons?: Prisma.LessonCreateNestedManyWithoutCreatorInput
}

export type UserUncheckedCreateWithoutProgressInput = {
  id?: string
  email: string
  username: string
  password: string
  firstName?: string | null
  lastName?: string | null
  role?: $Enums.UserRole
  createdAt?: Date | string
  updatedAt?: Date | string
  profile?: Prisma.UserProfileUncheckedCreateNestedOneWithoutUserInput
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutUserInput
  submissions?: Prisma.QuizSubmissionUncheckedCreateNestedManyWithoutUserInput
  createdPaths?: Prisma.LearningPathUncheckedCreateNestedManyWithoutCreatorInput
  createdModules?: Prisma.ModuleUncheckedCreateNestedManyWithoutCreatorInput
  createdLessons?: Prisma.LessonUncheckedCreateNestedManyWithoutCreatorInput
}

export type UserCreateOrConnectWithoutProgressInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutProgressInput, Prisma.UserUncheckedCreateWithoutProgressInput>
}

export type UserUpsertWithoutProgressInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutProgressInput, Prisma.UserUncheckedUpdateWithoutProgressInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutProgressInput, Prisma.UserUncheckedCreateWithoutProgressInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutProgressInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutProgressInput, Prisma.UserUncheckedUpdateWithoutProgressInput>
}

export type UserUpdateWithoutProgressInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.UserProfileUpdateOneWithoutUserNestedInput
  enrollments?: Prisma.EnrollmentUpdateManyWithoutUserNestedInput
  submissions?: Prisma.QuizSubmissionUpdateManyWithoutUserNestedInput
  createdPaths?: Prisma.LearningPathUpdateManyWithoutCreatorNestedInput
  createdModules?: Prisma.ModuleUpdateManyWithoutCreatorNestedInput
  createdLessons?: Prisma.LessonUpdateManyWithoutCreatorNestedInput
}

export type UserUncheckedUpdateWithoutProgressInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.UserProfileUncheckedUpdateOneWithoutUserNestedInput
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutUserNestedInput
  submissions?: Prisma.QuizSubmissionUncheckedUpdateManyWithoutUserNestedInput
  createdPaths?: Prisma.LearningPathUncheckedUpdateManyWithoutCreatorNestedInput
  createdModules?: Prisma.ModuleUncheckedUpdateManyWithoutCreatorNestedInput
  createdLessons?: Prisma.LessonUncheckedUpdateManyWithoutCreatorNestedInput
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  enrollments: number
  progress: number
  submissions: number
  createdPaths: number
  createdModules: number
  createdLessons: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  enrollments?: boolean | UserCountOutputTypeCountEnrollmentsArgs
  progress?: boolean | UserCountOutputTypeCountProgressArgs
  submissions?: boolean | UserCountOutputTypeCountSubmissionsArgs
  createdPaths?: boolean | UserCountOutputTypeCountCreatedPathsArgs
  createdModules?: boolean | UserCountOutputTypeCountCreatedModulesArgs
  createdLessons?: boolean | UserCountOutputTypeCountCreatedLessonsArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountEnrollmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EnrollmentWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountProgressArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProgressWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountSubmissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuizSubmissionWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountCreatedPathsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LearningPathWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountCreatedModulesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ModuleWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountCreatedLessonsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LessonWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  username?: boolean
  password?: boolean
  firstName?: boolean
  lastName?: boolean
  role?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  profile?: boolean | Prisma.User$profileArgs<ExtArgs>
  enrollments?: boolean | Prisma.User$enrollmentsArgs<ExtArgs>
  progress?: boolean | Prisma.User$progressArgs<ExtArgs>
  submissions?: boolean | Prisma.User$submissionsArgs<ExtArgs>
  createdPaths?: boolean | Prisma.User$createdPathsArgs<ExtArgs>
  createdModules?: boolean | Prisma.User$createdModulesArgs<ExtArgs>
  createdLessons?: boolean | Prisma.User$createdLessonsArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  username?: boolean
  password?: boolean
  firstName?: boolean
  lastName?: boolean
  role?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  username?: boolean
  password?: boolean
  firstName?: boolean
  lastName?: boolean
  role?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectScalar = {
  id?: boolean
  email?: boolean
  username?: boolean
  password?: boolean
  firstName?: boolean
  lastName?: boolean
  role?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "email" | "username" | "password" | "firstName" | "lastName" | "role" | "createdAt" | "updatedAt", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profile?: boolean | Prisma.User$profileArgs<ExtArgs>
  enrollments?: boolean | Prisma.User$enrollmentsArgs<ExtArgs>
  progress?: boolean | Prisma.User$progressArgs<ExtArgs>
  submissions?: boolean | Prisma.User$submissionsArgs<ExtArgs>
  createdPaths?: boolean | Prisma.User$createdPathsArgs<ExtArgs>
  createdModules?: boolean | Prisma.User$createdModulesArgs<ExtArgs>
  createdLessons?: boolean | Prisma.User$createdLessonsArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    profile: Prisma.$UserProfilePayload<ExtArgs> | null
    enrollments: Prisma.$EnrollmentPayload<ExtArgs>[]
    progress: Prisma.$ProgressPayload<ExtArgs>[]
    submissions: Prisma.$QuizSubmissionPayload<ExtArgs>[]
    createdPaths: Prisma.$LearningPathPayload<ExtArgs>[]
    createdModules: Prisma.$ModulePayload<ExtArgs>[]
    createdLessons: Prisma.$LessonPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    email: string
    username: string
    password: string
    firstName: string | null
    lastName: string | null
    role: $Enums.UserRole
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UserCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const userWithIdOnly = await prisma.user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UserUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const userWithIdOnly = await prisma.user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  profile<T extends Prisma.User$profileArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$profileArgs<ExtArgs>>): Prisma.Prisma__UserProfileClient<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  enrollments<T extends Prisma.User$enrollmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$enrollmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EnrollmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  progress<T extends Prisma.User$progressArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$progressArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgressPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  submissions<T extends Prisma.User$submissionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$submissionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizSubmissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  createdPaths<T extends Prisma.User$createdPathsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$createdPathsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LearningPathPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  createdModules<T extends Prisma.User$createdModulesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$createdModulesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModulePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  createdLessons<T extends Prisma.User$createdLessonsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$createdLessonsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LessonPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'String'>
  readonly email: Prisma.FieldRef<"User", 'String'>
  readonly username: Prisma.FieldRef<"User", 'String'>
  readonly password: Prisma.FieldRef<"User", 'String'>
  readonly firstName: Prisma.FieldRef<"User", 'String'>
  readonly lastName: Prisma.FieldRef<"User", 'String'>
  readonly role: Prisma.FieldRef<"User", 'UserRole'>
  readonly createdAt: Prisma.FieldRef<"User", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"User", 'DateTime'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
}

/**
 * User createManyAndReturn
 */
export type UserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User updateManyAndReturn
 */
export type UserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.profile
 */
export type User$profileArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProfile
   */
  select?: Prisma.UserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProfile
   */
  omit?: Prisma.UserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProfileInclude<ExtArgs> | null
  where?: Prisma.UserProfileWhereInput
}

/**
 * User.enrollments
 */
export type User$enrollmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Enrollment
   */
  select?: Prisma.EnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Enrollment
   */
  omit?: Prisma.EnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EnrollmentInclude<ExtArgs> | null
  where?: Prisma.EnrollmentWhereInput
  orderBy?: Prisma.EnrollmentOrderByWithRelationInput | Prisma.EnrollmentOrderByWithRelationInput[]
  cursor?: Prisma.EnrollmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EnrollmentScalarFieldEnum | Prisma.EnrollmentScalarFieldEnum[]
}

/**
 * User.progress
 */
export type User$progressArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Progress
   */
  select?: Prisma.ProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Progress
   */
  omit?: Prisma.ProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgressInclude<ExtArgs> | null
  where?: Prisma.ProgressWhereInput
  orderBy?: Prisma.ProgressOrderByWithRelationInput | Prisma.ProgressOrderByWithRelationInput[]
  cursor?: Prisma.ProgressWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProgressScalarFieldEnum | Prisma.ProgressScalarFieldEnum[]
}

/**
 * User.submissions
 */
export type User$submissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSubmission
   */
  select?: Prisma.QuizSubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSubmission
   */
  omit?: Prisma.QuizSubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSubmissionInclude<ExtArgs> | null
  where?: Prisma.QuizSubmissionWhereInput
  orderBy?: Prisma.QuizSubmissionOrderByWithRelationInput | Prisma.QuizSubmissionOrderByWithRelationInput[]
  cursor?: Prisma.QuizSubmissionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.QuizSubmissionScalarFieldEnum | Prisma.QuizSubmissionScalarFieldEnum[]
}

/**
 * User.createdPaths
 */
export type User$createdPathsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LearningPath
   */
  select?: Prisma.LearningPathSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LearningPath
   */
  omit?: Prisma.LearningPathOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LearningPathInclude<ExtArgs> | null
  where?: Prisma.LearningPathWhereInput
  orderBy?: Prisma.LearningPathOrderByWithRelationInput | Prisma.LearningPathOrderByWithRelationInput[]
  cursor?: Prisma.LearningPathWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LearningPathScalarFieldEnum | Prisma.LearningPathScalarFieldEnum[]
}

/**
 * User.createdModules
 */
export type User$createdModulesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Module
   */
  select?: Prisma.ModuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Module
   */
  omit?: Prisma.ModuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModuleInclude<ExtArgs> | null
  where?: Prisma.ModuleWhereInput
  orderBy?: Prisma.ModuleOrderByWithRelationInput | Prisma.ModuleOrderByWithRelationInput[]
  cursor?: Prisma.ModuleWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ModuleScalarFieldEnum | Prisma.ModuleScalarFieldEnum[]
}

/**
 * User.createdLessons
 */
export type User$createdLessonsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lesson
   */
  select?: Prisma.LessonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lesson
   */
  omit?: Prisma.LessonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LessonInclude<ExtArgs> | null
  where?: Prisma.LessonWhereInput
  orderBy?: Prisma.LessonOrderByWithRelationInput | Prisma.LessonOrderByWithRelationInput[]
  cursor?: Prisma.LessonWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LessonScalarFieldEnum | Prisma.LessonScalarFieldEnum[]
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
